components/layermanager/layermanager.js
components/layermanager/partials/layermanager.html
components/sidebar/partials/sidebar.html
examples/pilsen_traffic/app.js
examples/pilsen_traffic/index.html
examples/pilsen_traffic/partials/basemap-menu.html
examples/pilsen_traffic/partials/top-menu.html
examples/pilsen_traffic/partials/traffic-menu.html
examples/pilsen_traffic/pilsen.css

Layer manager rewritten to support Service architecture and so better reuseability. 
New Controls for Pilsen app added as test

Lay to service

---

components/datasource_selector/datasource_selector.js
components/datasource_selector/partials/datasource_selector.html
css/app.css

Also content of all the tabs was visible by default and moude pointer over tabs
should be a "hand" not a cursor
fixes #142

Fix misaligned datasources tabs

---

components/hscesium/hs_cesium_layers.js

Dont use newTerrainProviderOptions when calling createWorldTerrain

---

components/legend/legend.component.js
components/legend/partials/legend.html
components/legend/partials/legendmd.html

No legend warning

---

app.js
components/layermanager/layer-editor.component.js
components/layermanager/layermanager.component.js
components/layermanager/partials/layer-editor.html
components/styles/partials/styler.html
components/styles/styler.component.js

Icons are visible now.

---

components/layermanager/layer-editor.component.js
components/layermanager/layermanager.component.js
components/layermanager/partials/layer-editor.html
components/layermanager/partials/layermanagermd.html
components/utils/layer-utils.service.js

Tried to make it work, but still no luck! Need some guidance!

Issue has not been fixed refs #267

---

components/legend/legend.service.js
components/query/feature.component.js.js
components/query/partials/feature.html
components/query/query-base.service.js
components/query/query-vector.service.js

Added dropdown button for export formats

---

components/legend/legend.service.js
components/legend/partials/layer-directive.html
components/styles/partials/styler.html
components/styles/styler.component.js

VectorLayers should be displayed in Legend too 

---

components/layers/hs.source.SparqlJson.js

This is a minimal bugfix of issue #307. Needs further rework though.

SparqlJson update

---

components/legend/legend-layer-vector.directive.js
components/legend/legend-layer.directive.js
components/legend/legend.component.js
components/legend/legend.module.js
components/legend/legend.service.js
components/legend/partials/layer-directive.html
components/legend/partials/layer-vector-directive.html
components/legend/partials/legend.html
components/utils/utils.service.js
package.json

Haven't fixed the displayed geometry sizes and proportions!

Styles and feature geometries are visible in legend

---

components/query/feature.component.js
components/query/feature.component.js.js
components/query/partials/feature.html
components/query/query-vector.service.js
components/query/query.module.js

Attributes can be added to a feature, but you have to re enter the info panel to see the new attributes.

Issue 328/new attributes to vector layer

---

components/draw/vgi-draw.component.js
components/save-map/partials/form.html
components/save-map/partials/simpleform.html
components/save-map/save-map-manager.service.js
components/save-map/save-map.component.js
components/save-map/save-map.service.js

Added select/deselect all layers button to save-map component

---

components/layout/layout.service.js
components/layout/partials/layout.html
components/sidebar/partials/minisidebar.html
components/sidebar/partials/sidebar.html
components/sidebar/sidebar.controller.js
css/app.css

- if there is more sidebar buttons in sidebar than fits the screen corresponding buttons should be hidden inside hamburger menu 
- fixed panelspace height on mobile
- fixed language code not showing in sidebar

Minisidebar

---

components/core/core.js
components/layout/layout.service.js
components/sidebar/sidebar.controller.js
css/app.css

Change calculation of app height on mobile devices

---

components/core/core.js
components/layout/layout.service.js

fullScreenMap method was moved to layout.service but sizeOption parameter and init function not

fix fullScreenMap function

---

components/layout/partials/layout.html
components/map/map.service.js
components/query/feature-popup.component.js
components/query/partials/feature-popup.html
components/query/query-base.service.js
components/query/query-vector.service.js
components/query/query.module.js

Popup still is hidden, need help with that!

Added featurePopup component and map pointerMove listener

---

components/layermanager/layermanager.service.js
components/layermanager/partials/layer-editor.html
components/measure/measure.service.js

Displaying of measure values is not working on mobile devices

Mobile measure

---

components/add-layers/wms/add-wms-layer.directive.html

Fixed "+" button positioning

---

components/map/map.service.js
css/app.css

used the ol example implementation (https://openlayers.org/en/latest/examples/custom-controls.html ) for easy positioninig

add default view custom control

---

components/map/map.controller.js
components/map/map.service.js

resolves #474 
needs further polishing though:
- as of now it won't work for Core.puremapApp 
- the notification dialog should be displayed in another manner

Issue 474/ctrl+mouse for zoom

---

components/core/core.js
components/layermanager/layermanager-gallery.directive.js
components/layout/layout.controller.js
components/layout/layout.service.js
hslayers.html

- Fix size calculation of hsl map and panelspace when app included in CMS like Wordpress.
- added config parameter for sidebarExpanded state
Further style changes to the panelspace content may be necessary

HSL sizes in container sizemode

---

components/draw/draw.controller.js
components/draw/draw.service.js
components/draw/partials/draw.directive.html

Configurable individual styling of drawn features

---

components/core/core.service.js
components/draw/partials/shape-toolbar.html
components/geolocation/geolocation.directive.js
components/layout/layout.service.js
components/layout/partials/layout.html
components/map/map.controller.js
components/map/map.service.js
components/map/partials/map.html
components/search/partials/searchinput.html
components/toolbar/partials/toolbar.html

fixes #555
Settings to be described in wiki:
componentsEnabled: {
sidebar: true/false,
toolbar: true/false,
guiOverlay: true/false,
drawToolbar: true/false,
searchToolbar: true/false,
measureToolbar: true/false,
golocationButton: true/false
},
mapInteractionsEnabled: true/false,
mapControlsEnabled: true/false,

Split pureMap into multiple config params

---

components/layermanager/partials/layermanager.html

Sorry for this one, ill fix my linter

fix deletion

---

components/add-layers/wmts/add-wmts-layer.directive.html
components/layermanager/layer-editor.sub-layer-checkboxes.directive.js
components/layermanager/layer-editor.sub-layer.service.js
components/layermanager/layermanager-gallery.directive.js
components/layermanager/layermanager-layerlist.directive.js
components/layermanager/layermanager-metadata.service.js
components/layermanager/layermanager.component.js
components/layermanager/layermanager.service.js
components/layermanager/partials/layer-editor.html
components/layermanager/partials/layerlist.html
components/layermanager/partials/layermanager.html
components/layout/layout.directive.js
css/app.css

Couple of changes:
- collapsible layer folders plus some related css changes
- possiblity to parse multiple LAYER params to sublayers and metadata
- change sublayer checkbox behavior 
- import ol.css after isobootstrap to prevent overriding

Layermanager changes

---

app.js
components/query/partials/feature-popup.html
components/query/query-base.service.js
components/query/query-vector.service.js
components/utils/utils.service.js
components/utils/utils.spec.js
css/app.css

These changes are required to present an HSLayers-based map of members in the plan4all website.
It primarily enhances settings and functionality of pop-ups.

Changes for P4A website

---

components/compositions/partials/compositions.html
css/whhg-font/css/whhg.css

Fix missing icons in compositions and sidebar

---

components/map/map.service.js
components/map/map.spec.ts

Test layerDuplicate function and map service

---

components/layermanager/layer-editor.component.ts
components/layermanager/partials/layer-editor.html

fix _co.inResolution is not a function error

---

components/styles/styler.component.ts

Fix circle style line width with decimals

---

components/compositions/partials/compositions.html

Fixed pager displaying in the compositions panel. We will need to publish release 1.24.2 with this fix. Any ideas what next to include in the release?

Fix compositions pagination

---

components/layermanager/index.ts
components/layermanager/layer-descriptor.interface.ts
components/layermanager/layer-editor.component.ts
components/layermanager/layer-editor.service.ts
components/layermanager/layer-editor.sub-layer.service.ts
components/layermanager/layer-selector.service.ts
components/layermanager/layermanager-layerlist.component.ts
components/layermanager/layermanager-metadata.service.ts
components/layermanager/layermanager.component.ts
components/layermanager/layermanager.module.ts
components/layermanager/layermanager.service.ts
components/layermanager/partials/layerlist.html
components/legend/legend.service.ts
components/legend/partials/legend.html

Issue 881/hs layer selector service

---

components/compositions/compositions.component.js
components/compositions/endpoints/compositions-micka.service.js
components/compositions/partials/compositions.html
components/draw/draw-layer-metadata.component.js
components/draw/draw.controller.js
scripts/webpack.prod.js

Fixes compositions loading to allow multiple Micka endpoints
@jmacura Add another commits/fixes if you have some for 1.24. Thanks

Version 1.24.3

---

ajs-app.ts
components/core/core.service.ts
components/draw/partials/draw-toolbar.html
components/hscesium/partials/cesium.html
components/layermanager/layermanager-gallery.component.ts
components/layermanager/partials/basemap-gallery.html
components/layout/layout.controller.js
components/layout/layout.directive.js
components/layout/layout.service.js
components/layout/partials/layout.html
components/legend/partials/legend.html
components/map/map.service.js
components/permalink/share-url.service.ts
components/sidebar/partials/minisidebar.html
components/sidebar/partials/sidebar.html
components/sidebar/sidebar.component.ts
components/sidebar/sidebar.service.ts
components/toolbar/partials/toolbar.html
components/toolbar/toolbar.component.ts
config.service.ts
css/app.css
css/mobile.css
hslayers.html
package-lock.json

Notes
- hs-app element needs display and height propery to be set
- fixes #804 #461 
TBD
- delete unused rules in app.css

Refactor layout - replace js with css where possible

---

components/save-map/index.ts

Add missing downgradeInjectable()

---

components/compositions/compositions.service.js
components/permalink/share.service.ts
components/utils/utils.service.ts

#refs980
Could someone please test it with SSL connection, so I know, that URL is working?

Corrected returned HsUtilsService.shortUrl promise implementation

---

components/hscesium/hscesium.component.ts
components/permalink/share-url.service.ts
components/permalink/share.component.ts
components/permalink/share.module.ts
components/permalink/share.service.ts
components/save-map/save-map.service.ts
components/search/search-input.component.ts
components/search/search.component.ts
components/utils/utils.service.ts

partially resolves #998 
The URL won't get appended but updated.
? and # marks are treated correctly.
Existing URL gets parsed as expected.
Yet the history of browsing is not acting as expected (moving through browser history does not change the view).

Fix URL generation

---

components/draw/draw-toolbar.component.ts
components/draw/draw.service.ts
components/draw/partials/draw-toolbar.html

Added small toggle for changing draw toolbars buttons class. 

---

common/history-list/history-list.service.ts

Fixed history module wrong cookie data usage

---

common/history-list/history-list.module.ts
components/add-layers/add-layers.module.ts
components/add-layers/arcgis/add-layers-arcgis.service.js
components/add-layers/wms/add-layers-wms.service.js
components/geolocation/geolocation.module.ts
components/permalink/share.module.ts
components/save-map/index.ts
components/search/search.module.ts
components/sidebar/index.ts
components/sidebar/sidebar.module.ts
package-lock.json
package.json

I suggest removing angular-cookies from project, as they have no use anymore

Removed angular-cookies from Hslayers-ng project

---

components/query/feature-popup.component.ts
components/query/partials/feature-popup.html

Added popup close button when using popup click control

---

components/layout/partials/layout.html

Move hs-dialog-area to contentWrapper

---

components/draw/draw-toolbar.component.ts
components/draw/draw.service.ts
components/layermanager/layer-editor-vector-layer.service.ts
components/layermanager/partials/layermanagermd.html
components/styles/styler-color.component.ts
components/styles/styler.component.ts
components/styles/styler.spec.ts

Fixed feature styling bugs

---

assets/locales/cs.json
assets/locales/en.json
assets/locales/lv.json
components/draw/draw-toolbar.component.ts
components/draw/draw.service.ts
components/layermanager/layer-editor-vector-layer.service.ts
components/layermanager/partials/layermanagermd.html
components/measure/partials/measure.html
components/query/query-vector.service.ts
components/styles/partials/color.html
components/styles/partials/styler.html
components/styles/styler-color.component.ts
components/styles/styler-color.service.ts
components/styles/styler.component.ts
components/styles/styler.service.ts
components/styles/styler.spec.ts
components/styles/styles.module.ts
css/app.css

Sanitize styler icons and rework styler

---

components/layermanager/layer-editor-vector-layer.service.ts
components/styles/partials/styler.html
components/styles/styler.component.ts
components/styles/styler.spec.ts

Wanted to add to #1066 just forgot to send comment ^^

Allow cluster styling

---

package-lock.json
package.json

Sync the version number between master and develop

Release 2.4.0

---

components/layermanager/layer-editor-vector-layer.service.ts
components/layermanager/layer-editor.spec.ts
components/styles/styler.component.ts
components/styles/styler.service.mock.js
components/styles/styler.service.ts
components/styles/styler.spec.ts

Issue 1081/move styling functions

---

assets/locales/cs.json
assets/locales/en.json
common/confirm/confirm-dialog.html
components/draw/draw-layer-metadata.component.ts
components/draw/draw.service.ts
components/draw/draw.spec.ts
components/draw/partials/draw-toolbar.html
components/draw/partials/draw.html
components/layermanager/layermanager.service.ts
components/save-map/layman.service.ts
config.service.ts

Mostly changes requested by Petr Vacha
...There have also been a debate about the drawing finishing using right click. Whether ill be more intuitive to preserve last sketch vertex (add it to the feature before finishing drawing)  or to preserve only the 'stable' ones  (ones that are added by left click).
In the PR the first option is used.  On the other hand tester who tested it on v1.24 asked for the second one.

Draw adjustments

---

components/core/core.service.ts
components/layermanager/dimensions/layer-editor-dimensions.component.ts
components/layermanager/layermanager-gallery.component.ts
components/layermanager/layermanager.service.ts
components/layermanager/partials/basemap-gallery.html
components/layermanager/partials/layer-editor.html
components/layermanager/partials/layermanager.html
components/layout/layout.service.js
css/app.css

- Made base map inside of layermanager default again
- Added possibility to make basemap grayscale into layermanager
- Integrated layer-editor into basemap gallery so we have all potions avaliable for both basemap list types

Map gallery update

---

app.js

Required by @jmacura/sieusoil-website-map
Shall be ported to 2.x series as well.

Expose ol.style.Icon in the hslayersNgConfig()

---

assets/locales/en.json
assets/locales/lv.json
components/sensors/partials/unit-dialog.html
components/sensors/partials/unit-list-item.html
components/sensors/sensors-unit-list-item.component.ts
components/sensors/sensors.service.ts
components/sensors/unit-dialog.service.ts

Create Agregations min/max/avg for sensor readings

---

app.js
components/layers/hs.source.SparqlJson.js

Required by hub.plan4all.eu
- Expose SparqlJson in hslayersNgConfig()

SPARQL source fixes

---

components/compositions/compositions-parser.service.js
components/compositions/compositions.module.js
components/compositions/compositions.service.js
components/compositions/error-dialog.component.js
components/compositions/partials/dialog_error.html
components/layermanager/layer-editor-vector-layer.service.js
components/layermanager/layer-editor.component.js
components/layermanager/layer-editor.sub-layer-checkboxes.directive.js
components/layermanager/layermanager-gallery.directive.js
components/layermanager/layermanager-metadata.service.js
components/layermanager/layermanager.service.js
components/layermanager/partials/basemap-gallery.html
components/layermanager/partials/layer-editor.html
components/layermanager/partials/sub-layer-checkboxes.html
components/query/query-wms.service.js
components/styles/styler.component.js
components/styles/styles.module.js
components/styles/styles.service.js
components/utils/utils.service.js
css/app.css

- clustering
- wms layer max resolution
- Add support for .wmc compositions
- Add compositions error dialog
- sublayers styling react to resolution changes

1.25 fixes

---

components/draw/draw.service.js

Fix saving circle geometry to Layman

---

components/query/query-base.service.js
components/query/query-vector.service.js

Have created a way of calling a custom action on single feature clicked on the Hslayers map. To use this functionality, a layer must be defined inside app.js and layer attribute "onFeatureSelected" must be set to be a custom function, shown in the example.png.

Added customFeatureAction for clicked feature

---

components/query/query-vector.service.ts

Added onFeatureSelect attribute for layer

---

components/query/feature-popup.component.ts
components/query/query-base.service.ts

fixes #1249 
It would be great if we can release minor bugfix release 2.4.1 with this PR. Today 😆

Fix issue 1249: Pop-up window disappearing

---

assets/locales/cs.json
components/language/language.service.ts

Add missing cs translations and improve some incorrect cs translations

Add missing cs translations

---

css/app.scss

Remove bsi from scss rules

---

components/query/query-base.service.ts
components/query/query-wms.service.ts

Fix pop-up in Chromium-based browsers

---

components/compositions/compositions.spec.ts
components/layermanager/layer-editor-styles.service.ts
components/layermanager/layer-editor.spec.ts
components/layermanager/layer-list.spec.ts
components/layermanager/layermanager.service.ts
components/permalink/share-url.service.ts
components/save-map/save-map.service.ts
components/styles/partials/styler.html
components/styles/styler-color.service.ts
components/styles/styler.component.ts
components/styles/styler.service.ts
components/styles/styler.spec.ts

Main improvement - Made functionality for improved existing layer style check. In cases when layer style has icon image, decode it and extract style properties, that will be reapplied in Styler panel.
Created for projects that loads map compositions with styled layers.

Serialize style fix

---

css/app.scss

We have managed to miss this one

Include whhg font css

---

projects/hslayers/src/common/history-list/history-list.service.ts
projects/hslayers/src/common/wms/get-capabilities.service.ts
projects/hslayers/src/components/add-layers/add-layers.component.ts
projects/hslayers/src/components/add-layers/add-layers.module.ts
projects/hslayers/src/components/add-layers/common/add-layers-common.module.ts
projects/hslayers/src/components/add-layers/common/add-layers-url.component.ts
projects/hslayers/src/components/add-layers/common/capabilities-error-dialog.component.ts
projects/hslayers/src/components/add-layers/common/capabilities-error-dialog.html
projects/hslayers/src/components/add-layers/partials/add-layers.directive.html
projects/hslayers/src/components/add-layers/wfs/add-layers-wfs.component.ts
projects/hslayers/src/components/add-layers/wfs/add-layers-wfs.module.ts
projects/hslayers/src/components/add-layers/wfs/add-layers-wfs.service.ts
projects/hslayers/src/components/add-layers/wfs/add-wfs-layer.directive.html
projects/hslayers/src/components/add-layers/wms/add-layers-wms.component.ts
projects/hslayers/src/components/add-layers/wms/add-layers-wms.service.ts
projects/hslayers/src/components/add-layers/wmts/add-layers-wmts.component.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.component.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts

port of https://github.com/hslayers/hslayers-ng/pull/1311

Parse WMS and WFS layers from URL parameters

---

components/map/map.service.ts

Port of https://github.com/hslayers/hslayers-ng/commit/dd908ef5abfa3525d770beb0347587fc8f0a2f65

Proxy wmts layers even after source change

---

components/add-layers/wfs/add-layers-wfs.component.ts
components/draw/draw.service.ts
components/draw/partials/draw-layer-metadata.html
components/layermanager/layer-list.spec.ts
components/layermanager/layermanager.service.ts
components/save-map/layer-synchronizer.service.ts

Removing layer, which is set as "selectedLayer" for drawing, using "Remove all layers" button in layermanager doesnt remove its refference in drawing tool.  After the layer is added to the  map once again it get kinda duplicated and newly added drawings are not visible

Drawings not visible

---

components/add-layers/wms/add-layers-wms.service.ts

In case of unusually structured services eg. https://localhost:8085/https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?request=GetCapabilities&service=WMS&version=1.3.0

Check one level deeper for queriable layers in wms capabilities

---

components/map/map.service.ts

Unintentionally deleted in #1391. My bad , sorry

Add missing function call

---

projects/hslayers/src/components/add-layers/common/nested-layers-table.directive.html
projects/hslayers/src/components/add-layers/wms/add-wms-layer.directive.html
projects/hslayers/src/components/draw/partials/draw.html
projects/hslayers/src/components/language/partials/languagemd.html
projects/hslayers/src/components/layermanager/dimensions/layer-editor-dimensions.html
projects/hslayers/src/components/layermanager/layermanager-physical-layerlist.component.ts
projects/hslayers/src/components/layermanager/partials/layer-editor.html
projects/hslayers/src/components/layermanager/partials/layermanager.html
projects/hslayers/src/components/layermanager/partials/physical-layerlist.html
projects/hslayers/src/components/layermanager/partials/sub-layer-checkboxes.html
projects/hslayers/src/components/measure/partials/measuremd.html
projects/hslayers/src/components/permalink/partials/directive.html
projects/hslayers/src/components/query/partials/attribute-row.html
projects/hslayers/src/components/query/partials/feature.html
projects/hslayers/src/components/query/partials/infopanel.html
projects/hslayers/src/components/save-map/partials/form.html
projects/hslayers/src/components/save-map/partials/panel.html
projects/hslayers/src/components/save-map/partials/simpleform.html
projects/hslayers/src/components/search/partials/searchinput.html
projects/hslayers/src/components/trip_planner/partials/trip_planner.html

Also fixed a small LM physical layer list bug.

Provided name attribute or set ngModelOptions for users inputs to fix issued errors

---

.compodocrc.json
package.json
projects/hslayers-cesium/.compodocrc.json
projects/hslayers-sensors/.compodocrc.json
projects/hslayers/.compodocrc.json
scripts/docs_index_template.html
scripts/gen-doc.js

Enhancement of the doc script so it creates three separate documentations with a common disambiguation homepage.

Enhance doc script

---

package.json

Add hslayers-ng-logo.png to npm files (1.27)

---

package.json

Add hslayers-ng-logo.png to npm files (2.5)

---

projects/hslayers/src/components/save-map/save-map.service.ts

Save layers before page reload

---

projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
projects/hslayers/src/components/save-map/layman.service.ts

Basically just try catch blocks here, but sadly it shows like a lot of changes.

Fix new layman layer pushing

---

package-lock.json
projects/hslayers-server/.env.example
projects/hslayers-server/package-lock.json
projects/hslayers-server/package.json
projects/hslayers-server/server.js
projects/hslayers-server/src/share.js
projects/hslayers-server/src/views/socialShare.pug

First version of the Status Manager replacement. I have been testing as a separate application so far.

Add map sharing component to the hslayers-server

---

projects/hslayers/src/components/query/query.component.ts

Can You replicate the 404 popup with these changes?

Do not show empty wms popup

---

projects/hslayers/src/components/layermanager/layermanager-physical-layerlist.component.ts
projects/hslayers/src/components/layermanager/layermanager-physical-layerlist.service.ts
projects/hslayers/src/components/layermanager/layermanager.module.ts
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/layermanager/partials/layermanager.html
projects/hslayers/src/components/layermanager/partials/physical-layerlist.html
projects/hslayers/src/public-api.ts

to new physicalLayerListService
Added new functions that allows to move layer to the start or end of the list

Moved all layer list shifting functionlity

---

components/save-map/save-map.service.ts
config.service.ts

Layer cookies optional (2.5)

---

projects/hslayers/src/components/compositions/compositions-catalogue.service.ts
projects/hslayers/src/components/compositions/compositions-list-item.component.ts
projects/hslayers/src/components/compositions/compositions.component.ts
projects/hslayers/src/components/compositions/compositions.html
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
projects/hslayers/src/css/app.scss

endpoint returned matched value
Removed redundant code
Only should be merged after #1467 branch

Fill composition list based on endpoint count

---

projects/hslayers/src/components/save-map/save-map.service.ts
projects/hslayers/src/config.service.ts

Layer cookies optional (3.0)

---

common/wmts/get-capabilities.service.js
components/add-layers/wmts/add-layers-wmts.component.js
components/compositions/compositions-parser.service.js
components/compositions/endpoints/status-manager-micka-joint.service.js
components/compositions/layer-parser.service.js
components/compositions/partials/dialog_info.html
components/layermanager/layermanager.service.js
components/map/map.service.js
components/save-map/save-map.service.js

- Fix broken viewport when loading compositions #1498 
- Fix blank layer manager when added layer causes an error 
Should be also checked for 2.x and 3.x

Fix wrong viewport and layer list (1.27)

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/components/compositions/compositions-list-item.component.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/dialogs/dialog_warning.html
projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-status-manager.service.ts
projects/hslayers/src/components/compositions/endpoints/status-manager-micka-joint.service.ts
projects/hslayers/src/components/data/catalogue/layman/layman.service.ts
projects/hslayers/src/components/data/catalogue/micka/micka.service.ts
projects/hslayers/src/components/layout/toast/toast.service.ts
projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
projects/hslayers/src/components/save-map/partials/dialog_result.html

Added toast messages to inform user about any errors occurred while working with Compostions or Addlayers.
***NOTE** - In need of few CS translations!

Toast messages

---

projects/hslayers/src/components/sidebar/sidebar.service.ts

Additional panels button state was not set properly  thus always visible

Fix additional panel sidebar button visibility

---

components/layers/hs.source.SparqlJson.js

This PR brings a significant speed improvement for SparqlJson(), if used for loading SPOI data.

Use bif:st_may_intersect instead of geof:sfIntersects for foodie-cloud

---

components/layers/hs.source.SparqlJson.ts

Use bif:st_may_intersect instead of geof:sfIntersects for foodie-cloud (2.5)

---

components/legend/partials/layer-directive.html

This hotfix is against the obsolete version 2, but I was just working on that version and I felt it makes no harm to fix that if eventually there would come another point release in v2.
~~I suspect this fix would need a port to v3, but have to check first.~~

Fix ngStyle of layer legend (2.5)

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts
projects/hslayers/src/components/add-data/url/arcgis/add-data-url-arcgis.service.ts
projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.service.ts
projects/hslayers/src/components/add-data/url/wmts/add-data-url-wmts-service.ts
projects/hslayers/src/components/core/core.module.ts
projects/hslayers/src/components/core/core.service.ts
projects/hslayers/src/components/language/language.service.ts

feat: Add Slovak translations

---

projects/hslayers/src/common/widgets/filter.pipe.ts
projects/hslayers/src/common/widgets/ui-extensions.module.ts
projects/hslayers/src/components/layermanager/base-layer-descriptor.interface.ts
projects/hslayers/src/components/layermanager/layer-editor.service.ts
projects/hslayers/src/components/layermanager/layermanager-layerlist.component.ts
projects/hslayers/src/components/layermanager/layermanager.component.ts
projects/hslayers/src/components/layermanager/layermanager.module.ts
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/layermanager/partials/layerlist.html
projects/hslayers/src/components/layermanager/partials/layermanager.html
projects/hslayers/src/components/legend/legend-descriptor.interface.ts
projects/hslayers/src/components/legend/legend-layer.component.ts
projects/hslayers/src/components/legend/legend-layer.spec.ts
projects/hslayers/src/components/legend/legend.component.ts
projects/hslayers/src/components/legend/legend.module.ts
projects/hslayers/src/components/legend/legend.service.ts
projects/hslayers/src/components/legend/legend.spec.ts
projects/hslayers/src/components/legend/partials/layer-directive.html
projects/hslayers/src/components/legend/partials/legend.html
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/print/print.service.ts
projects/hslayers/src/components/save-map/save-map.service.ts

Legend layer fixes

---

projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.ts
projects/hslayers/src/components/layermanager/layermanager-wmst.service.ts

Populate layers time dimension definition if
it has none, but GetCapabilities has it.

feat: Create time dimension def from getCaps

---

.github/workflows/nodejs.yml
package-lock.json
package.json

This reverts commit ec18e72e6342d1839d915368a46d640fdb8d01ca.

Fix inconsistent package-lock

---

projects/hslayers/src/components/layout/toast/toast.service.ts

fix: Show only last 5 toast error messages

---

projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.spec.ts
projects/hslayers/src/components/add-data/vector/add-data-vector.service.ts

fix: Apply string function toLowerCase, for uploaded vector file names

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/add-data-list-item.component.ts
projects/hslayers/src/components/add-data/catalogue/add-data-list-item.html
projects/hslayers/src/components/add-data/url/arcgis/add-data-url-arcgis.directive.html
projects/hslayers/src/components/add-data/url/wfs/add-data-wfs-layer.directive.html
projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.directive.html
projects/hslayers/src/components/add-data/url/wmts/add-data-url-wmts.html
projects/hslayers/src/components/compositions/compositions-list-item.component.ts
projects/hslayers/src/components/compositions/compositions-list-item.html
projects/hslayers/src/components/layermanager/layermanager.service.ts

Just a small adjustment. No border radius on inner side of buttons , centered

Add data fixes Filip

---

projects/hslayers/src/components/layout/toast/toast.component.ts

fix: Toast message width

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/layer-extensions.ts
projects/hslayers/src/components/add-data/catalogue/add-data-catalogue.service.ts
projects/hslayers/src/components/add-data/url/wfs/add-data-url-wfs.service.ts
projects/hslayers/src/components/add-data/vector/add-data-vector.service.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/compositions/schema.json
projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/save-map/partials/form.html
projects/hslayers/src/components/save-map/save-map-advanced-form.component.ts
projects/hslayers/src/components/save-map/save-map-manager.service.ts
projects/hslayers/src/components/save-map/save-map.component.ts
projects/hslayers/src/components/save-map/save-map.service.ts

closes #1880 
closes #1879 
closes #1907

Layman compositions fixes

---

projects/hslayers/src/components/sidebar/partials/sidebar.component.scss

fix: Unreachable side-buttons on small screens

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/vector/VectorLayerDescriptor.ts
projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts
projects/hslayers/src/components/add-data/vector/add-data-vector.directive.html
projects/hslayers/src/components/add-data/vector/vector-layer-options.type.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

@DailisLangovskis  could you please add Latvian translations, thanks

Issue 1946

---

projects/hslayers/src/components/styles/filters/scale-denominator.component.ts
projects/hslayers/src/components/styles/symbolizers/color-picker.component.ts
projects/hslayers/src/components/styles/symbolizers/color-picker.html

fixes #1959 
https://stackoverflow.com/a/58270890/14023346

fix: Styler related problems

---

projects/hslayers/src/components/core/core.service.ts
projects/hslayers/src/components/geolocation/geolocation.component.ts
projects/hslayers/src/components/layermanager/partials/basemap-gallery.html
projects/hslayers/src/components/layout/layout.service.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/toolbar/partials/toolbar.html

Or componentsEnabled.guiOverlay is set to false
Or componentsEnabled.sidebar is set to false

Hide sidebar for multiple HsConfig settings

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts
projects/hslayers/src/components/add-data/common/capabilities-error-dialog.html
projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts

feat: Inform user about invalid or missing layman endpoint url

---

projects/hslayers/src/components/draw/draw.service.ts

fix(draw): Get drawables only after map is loaded

---

projects/hslayers/src/components/add-data/common/add-data-common.module.ts
projects/hslayers/src/components/add-data/common/add-data-wms-layer-highlight-directive.ts
projects/hslayers/src/components/add-data/common/nested-layers-table.component.ts
projects/hslayers/src/components/add-data/common/nested-layers-table.directive.html
projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.directive.html
projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.service.ts
projects/hslayers/src/components/utils/utils.service.ts
projects/hslayers/src/css/app.scss

refactor: Improve WMS layers table UI

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/file/shp/add-data-file-layer.directive.html
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.component.ts
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.service.ts
projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts
projects/hslayers/src/components/draw/draw-layer-metadata.component.ts
projects/hslayers/src/components/save-map/save-map-manager.service.ts

+ GUI improvements for adddata shp
fixes #2015

fix: Read SLD style file for shp

---

projects/hslayers-server/README.md

docs(server): Extend hslayers-proxy documentation

---

projects/test-app/src/hslayers-app/hslayers-app.component.ts

style(test-app):Remove unnecessary commented lines

---

projects/hslayers/src/components/add-data/url/add-data-url.service.ts
projects/hslayers/src/components/add-data/url/wfs/add-data-url-wfs.service.ts
projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.service.ts

Little change that fixes loading layers from url

fix: Properly select and add layer loaded through url param 'wms_layers'

---

projects/hslayers/src/common/layers/hs.source.SparqlJson.ts
projects/hslayers/src/components/legend/legend.service.ts

------------
Add type-definitions to common/layers and components/legend/legend.service
#2082 

Add type-defs

---

projects/hslayers-sensors/src/components/sensors/sensors.service.ts

Added missed out OL 6.6 related type changes to sensors.service in hslayers-sensors project

refactor(sensors): Create new layer for OL 6.6

---

projects/hslayers/src/components/map/map.spec.ts
projects/hslayers/src/components/permalink/share-url.service.mock.ts

test: Fix failed tests

---

package-lock.json
package.json
projects/hslayers/package-lock.json
projects/hslayers/package.json
projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/file/shp/add-data-file-layer.component.html
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.component.ts
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.module.ts
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.service.ts
projects/hslayers/src/components/save-map/layman-utils.ts
projects/hslayers/src/components/save-map/layman.service.ts

Use resumableJs library to upload data larger than 2mb to Layman
closes #2121 

feat: Use resumablejs to upload data larger than 2mb in chunks

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/file/shp/add-data-file-layer.component.html
projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.component.ts
projects/hslayers/src/components/draw/draw-toolbar.component.ts
projects/hslayers/src/components/draw/draw.component.ts
projects/hslayers/src/components/draw/partials/draw-layer-metadata.html
projects/hslayers/src/components/draw/partials/draw-toolbar.html
projects/hslayers/src/components/draw/partials/draw.html
projects/hslayers/src/css/app.scss

Issue 2147

---

projects/hslayers/src/common/layers/hs.source.WfsSource.ts

Just a small optimization to not use DOMParser when converting xml text to features. I don't remember why it was added, but seems that its redundant and makes getting features slower.

perf: Skip DOMParser intermediary step for WFS

---

projects/hslayers/src/common/layers/hs.source.WfsSource.ts
projects/hslayers/src/common/layers/public-api.ts
projects/hslayers/src/components/add-data/url/wfs/add-data-url-wfs.service.ts

Created new class wfsSource for url-wfs component needs.
None

feature: New WfsSource class extending Vector<Geometry>

---

projects/hslayers/src/components/styles/rule/rule-list-item/rule-list-item.component.html
projects/hslayers/src/components/styles/rule/rule.component.html
projects/hslayers/src/components/styles/rule/rule.component.ts
projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.ts
projects/hslayers/src/components/styles/symbolizers/line-symbolizer/line-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/line-symbolizer/line-symbolizer.component.ts

Missed out one commit fixing menus not closing for issue 2183

fix: Close dropdown menus

---

projects/hslayers/src/components/query/feature-list.component.ts
projects/hslayers/src/components/query/feature.component.ts

fix: Prevent query dropdown menus from overlaping

---

projects/hslayers/src/common/extent-utils.ts
projects/hslayers/src/common/layman/layman.service.ts
projects/hslayers/src/components/add-data/catalogue/add-data-catalogue.service.ts
projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts
projects/hslayers/src/components/add-data/common/add-data-common.service.ts
projects/hslayers/src/components/compositions/compositions-map.service.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-status-manager.service.ts
projects/hslayers/src/components/compositions/endpoints/status-manager-micka-joint.service.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/layout/toast/toast.service.ts
projects/hslayers/src/components/permalink/share.service.ts
projects/hslayers/src/components/query/feature-common.service.ts
projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/trip-planner/trip-planner.service.ts

This PR adds extent feature creation for layman data, such as layers or compositions.
refs #2259 

Missing extent features

---

projects/hslayers/src/components/add-data/common/advanced-options/advanced-options.component.html
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
projects/hslayers/src/components/draw/partials/draw-layer-metadata.html
projects/hslayers/src/components/permalink/partials/share.component.html
projects/hslayers/src/components/print/partials/printdialog.html

Use b5 floating labels in more components

refactor: Use b5 floating labels in more components

---

projects/test-app/src/hslayers-app/hslayers-app.component.ts
projects/test-app/src/hslayers-app/popup-widget.component.ts
projects/test-app/src/hslayers-app/popup-widget.html

Test example for new custom widgets
#2336 

Overridable popup widget list

---

projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/file/file-base.component.ts
projects/hslayers/src/components/add-data/url/add-data-url-base.component.ts
projects/hslayers/src/components/add-data/url/add-data-url.module.ts
projects/hslayers/src/components/add-data/url/arcgis/arcgis.component.ts
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/url/injection-tokens.type.ts
projects/hslayers/src/components/add-data/url/models/url-type-component.model.ts
projects/hslayers/src/components/add-data/url/public-api.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.component.html
projects/hslayers/src/components/add-data/url/wfs/wfs.component.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
projects/hslayers/src/components/add-data/url/wms/wms.component.ts
projects/hslayers/src/components/add-data/url/wms/wms.service.ts
projects/hslayers/src/components/add-data/url/wms/wms.spec.ts
projects/hslayers/src/components/add-data/url/wmts/wmts-service.ts
projects/hslayers/src/components/add-data/url/wmts/wmts.component.html
projects/hslayers/src/components/add-data/url/wmts/wmts.component.ts
projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
projects/hslayers/src/components/save-map/layman-layer-descriptor.interface.ts

This PR is for refactoring add-data url components introducing a super class component add-data-url-base.component, that helps removing duplicated code.
None

refactor: Added a new add-data-url-base component

---

package-lock.json
package.json
projects/hslayers/package-lock.json
projects/hslayers/package.json
projects/hslayers/src/components/draw/draw-edit/draw-edit.component.html
projects/hslayers/src/components/draw/draw-edit/draw-edit.component.ts

Splitting by a thickened line is undesirable, because it create a small gap between the resulting
polgygons halves
BREAKING CHANGE: Add polygon-splitter peer dependency `npm i polygon-splitter`
ref #2386

feat: Topologically correct splitting of polygons

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts

Fix micka query string for compositions and add-data.

fix: Micka query strings

---

package-lock.json
package.json
projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/file/file-base.component.ts
projects/hslayers/src/components/add-data/url/add-data-url-base.component.ts
projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/info/info.component.ts
projects/hslayers/src/components/layermanager/dimensions/layer-editor-dimensions.component.ts
projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.ts
projects/hslayers/src/components/layermanager/layermanager.component.ts
projects/hslayers/src/components/layout/dialogs/dialog-container.component.ts
projects/hslayers/src/components/layout/panels/panel-container.component.ts
projects/hslayers/src/components/legend/legend-layer/legend-layer.component.ts
projects/hslayers/src/components/measure/measure.component.ts
projects/hslayers/src/components/permalink/share-url.service.ts
projects/hslayers/src/components/query/query-base.service.ts
projects/hslayers/src/components/query/query-wms.service.ts
projects/hslayers/src/components/query/query.component.ts
projects/hslayers/src/components/save-map/save-map-advanced-form.component.ts
projects/hslayers/src/components/save-map/save-map.component.ts
projects/hslayers/src/components/search/search-results.component.ts
projects/hslayers/src/components/sidebar/sidebar.service.ts
projects/hslayers/src/components/styles/styler.component.ts

build: Upgrade to rxjs 7

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/common/layer-extensions.ts
projects/hslayers/src/components/map-swipe/map-swipe.component.html
projects/hslayers/src/components/map-swipe/map-swipe.component.ts
projects/hslayers/src/components/map-swipe/map-swipe.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Added feature, where the user can display layer for full map even for enabled map-swipe component
closes #2509 

Ability to display layer for full map, when map-swipe is enabled (Issue-2509)

---

package-lock.json
projects/hslayers/src/common/extent-utils.ts
projects/hslayers/src/components/map/map.service.ts

This also simplifies how original viewport
is stored for reseting map later on
fixes #2522 

fix: Private view properties not applied

---

projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts

Vector file upload

---

projects/hslayers/src/components/layermanager/layermanager.service.ts

Fixes the #2553 issue
closes #2553

Fix the loading layer icon (Issue-2553)

---

projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts

Missed out commif from @fzadrazil 
Fixes zoomToLayer for arcgis
closes #2459 

fix: Load extent of ArcGIS layers for zoom to button

---

projects/hslayers-server/.env.example
projects/hslayers-server/src/layman.js
projects/hslayers-server/src/share.js
projects/hslayers/src/components/save-map/status-manager.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Fixes few bugs regarding integration on Wagtail CMS instead of Liferay.

Server Wagtail

---

projects/hslayers-server/package-lock.json
projects/hslayers-server/package.json

Bump HSLayers Server version to 1.5.0
Bump dependencies
* better-sqlite3 7.1.2 => 7.5.0
* dotenv 8.2.0 => 14.2.0
* express 4.17.1 => 4.17.2
* express-session 1.17.1 => 1.17.2
* got 11.8.1 => 11.8.3
* http-proxy-middleware 1.0.6 => 2.0.1
* passport 0.4.1 => 0.5.2
* pug 3.0.1 => 3.0.2

HSLayers Server 1.5.0

---

projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/map/map.service.ts

PR fixes arcgis service expansion, if the services are located inside a folder
None

Fixes expanding arcgis services from folders

---

projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/components/add-data/common/common.service.ts
projects/hslayers/src/components/add-data/common/url/details/details.component.ts
projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
projects/hslayers/src/components/add-data/url/add-data-url.service.ts
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts

This PR resolves #2574 
closes #2574 

Allow adding Arcgis Image Services to map (Issue 2574)

---

projects/hslayers/src/components/layout/panels/panel-component.interface.ts
projects/hslayers/src/components/layout/panels/panel-container.component.ts
projects/hslayers/src/components/layout/panels/panel-container.service.interface.ts
projects/hslayers/src/components/layout/panels/panel-container.service.ts
projects/hslayers/src/hslayers.component.ts

Cleanup function for panels and reload list of panels when reloading hslayers

feat: Cleanup after panels

---

projects/hslayers/src/css/hslayers-bootstrap.scss
projects/hslayers/src/css/hslayers-wo-bootstrap.scss

fix: Widgets overlaping container

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/layman/delete-layer-response.type.ts
projects/hslayers/src/common/layman/public-api.ts
projects/hslayers/src/common/remove-multiple/public-api.ts
projects/hslayers/src/common/remove-multiple/remove-multiple-dialog.component.ts
projects/hslayers/src/common/remove-multiple/remove-multiple-dialog.html
projects/hslayers/src/common/remove-multiple/remove-multiple.module.ts
projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.ts
projects/hslayers/src/components/draw/draw-panel/draw-panel.component.html
projects/hslayers/src/components/draw/draw-toolbar/draw-toolbar.html
projects/hslayers/src/components/draw/draw.module.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/layout/toast/toast.html
projects/hslayers/src/components/layout/toast/toast.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/public-api.ts

This PR resolves the issue 2578 and also fixes the deletion of the layers, be waiting Laymans response with async/await.
Also added toast message, when layers are removed
closes #2578 

Ability to delete multiple layers at once (Issue-2578)

---

projects/hslayers/src/common/get-capabilities/arcgis-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wfs-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wms-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wmts-get-capabilities.service.ts
projects/hslayers/src/common/layers/hs.source.WfsSource.ts
projects/hslayers/src/common/layman/layman.service.ts
projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/url/wms/wms.spec.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/dialogs/delete-dialog.component.ts
projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-status-manager.service.ts
projects/hslayers/src/components/compositions/endpoints/status-manager-micka-joint.service.ts
projects/hslayers/src/components/core/core.module.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/permalink/share.service.ts
projects/hslayers/src/components/query/query-wms.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/save-map/save-map-manager.service.ts
projects/hslayers/src/components/save-map/status-manager.service.ts
projects/hslayers/src/components/trip-planner/trip-planner.service.ts
projects/hslayers/src/components/utils/utils.service.ts

This PR resolves issue #2583 and is rebased on delete many at once branch, due to some changes made there, that reflects in this PR as well.
closes #2583 

Replace toPromise with lastValueFrom (Issue-2583)

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json

The merge was faster than I finished i18n.
adds to #2594 refs #2578

Ability to delete multiple layers at once (Issue-2578): add cs translations

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/components/layermanager/layermanager.component.ts
projects/hslayers/src/components/layermanager/layermanager.html
projects/hslayers/src/components/layermanager/logical-list/layer-list.spec.ts
projects/hslayers/src/components/layermanager/logical-list/layerlist.html
projects/hslayers/src/components/layermanager/logical-list/layermanager-layerlist.component.ts
projects/hslayers/src/components/layermanager/logical-list/layermanager-layerlist.service.mock.ts
projects/hslayers/src/components/layermanager/logical-list/layermanager-layerlist.service.ts
projects/hslayers/src/components/layermanager/public-api.ts
projects/hslayers/src/components/layout/panels/panel-header.component.html
projects/hslayers/src/css/hslayers-bootstrap.scss

Resolves issue #2585 
closes #2585 

Ability to toggle all layer visibility (Issue 2585)

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/layer-descriptor.model.ts
projects/hslayers/src/components/draw/draw-panel/draw-panel.spec.ts
projects/hslayers/src/components/draw/draw.service.ts

This PR resolves issue #2609. Layer is checked if it is a vector layer, if not a dialog pops up and asks, if the user wants to add the layer anyway as raster layer.
closes #2609 

Check layer type before setting as drawing layer (Issue 2609)

---

projects/hslayers/src/components/layermanager/layermanager.service.ts

Copied layer sublayers are set for the new copy
closes #2631

Set sublayers to new copy (Issue-2631)

---

angular.json
projects/hslayers-material/src/lib/layermanager/layermanager.component.ts
projects/hslayers-material/src/lib/layermanager/layermanager.module.ts
projects/hslayers-material/src/lib/layout/attribution-dialog.html
projects/hslayers-material/src/lib/layout/layout.component.scss
projects/hslayers-material/src/lib/layout/layout.module.ts
projects/hslayers-material/src/lib/layout/overlay.component.html
projects/hslayers-material/src/lib/layout/overlay.component.scss
projects/hslayers-material/src/lib/layout/overlay.component.ts
projects/hslayers-material/src/lib/material-module.ts
projects/hslayers-material/src/public-api.ts

Bring hslayers-material up to date, minor fixes.

Develop material merge

---

projects/hslayers/src/components/layout/partials/layout.component.scss

fix: Panels space minw width

---

projects/hslayers-cesium/package.json

hslayers-cesium dependencies update to Angular 13 and resolution fix
none

Fix hslayers-cesium dependencies

---

projects/hslayers/src/components/save-map/save-map-manager.service.ts

Remove request call for Status manager methods that are no longer needed since we don't use SM anymore.
Closes #2796 

Remove obsolete Status Manager requests

---

projects/hslayers/src/components/add-data/common/url/details/details.component.html
projects/hslayers/src/components/add-data/common/url/details/details.component.ts

fix(add-data): Fix url details params translation

---

projects/hslayers/src/components/query/query-base.service.ts
projects/hslayers/src/components/query/query-popup.service.ts
projects/hslayers/src/components/query/query-vector.service.ts
projects/hslayers/src/components/query/query-wms.service.ts
projects/hslayers/src/components/query/query.component.ts

This PR resolves issue-2846, yet I an not sure if it doesnt break anything else, due to a removed event queryStatusChanges, which caused the issue.
Also any subscriptions made in query components service constructors, where moved to init methods and app ref is being checked.
closes #2846 

Show WMS query feature attributes (Issue-2846)

---

projects/hslayers/src/common/layman/layman-current-user.component.ts
projects/hslayers/src/common/layman/layman-login.component.ts

Resolves Layman login issue
closes #2870 

Provide correct data object for layman login (Issue-2870)

---

projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
projects/hslayers/src/components/add-data/url/types/recursive-options.type.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
projects/hslayers/src/components/add-data/url/wms/wms.service.ts
projects/hslayers/src/components/compositions/compositions-list-item.component.ts
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/save-map/save-map.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.html
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Csw compositions

---

projects/hslayers/package-lock.json
projects/hslayers/package.json

------------
ol-ext is required for IDW layer.
IDW layer was introduced in ol-ext@3.2.3
#2794 

Add ol-ext dependency

---

projects/hslayers/src/components/draw/draw.service.ts

Provided default sld for tmp draw layer
closes #2903 

fix: Provide default style for tmp draw layer (Issue-2903)

---

projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
projects/hslayers/src/components/compositions/compositions-catalogue.service.ts

Filtering should be fixed now.
closes #2932 

Filter duplicate layers or compositions (Issue-2932)

---

angular.json
projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
projects/hslayers/src/components/add-data/url/wmts/wmts.component.html
projects/hslayers/src/components/compositions/compositions-catalogue.service.ts
projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/layermanager/layermanager.html
projects/hslayers/src/components/layout/toast/toast.component.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/permalink/share-url.service.ts
projects/hslayers/src/components/query/default-info-panel-body/default-info-panel-body.component.html
projects/hslayers/src/components/query/feature/feature.component.html
projects/hslayers/src/components/styles/symbolizers/symbolizer-list-item/symbolizer-list-item.component.html

Some of the hacks will be reverted after the webinar, others will be merged.

Multiple fixes and hacks for webinar

---

projects/hslayers/src/components/layermanager/layermanager.component.ts
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/print/legend-styler/legend-styler.component.html
projects/hslayers/src/components/print/text-styler/text-styler.component.html
projects/hslayers/src/components/sidebar/mini-sidebar.component.ts
projects/hslayers/src/components/styles/symbolizers/color-picker/color-picker.component.html
projects/hslayers/src/css/hslayers-bootstrap.scss

This contains bug fixes when testing on whiteboard application

Whiteboard fixes

---

projects/hslayers/src/common/layman/access-rights/layman-access-rights.component.ts
projects/hslayers/src/common/layman/layman-current-user.html
projects/hslayers/src/css/hslayers-bootstrap.scss
projects/hslayers/src/css/hslayers-colors.scss
projects/hslayers/src/css/hslayers-wo-bootstrap.scss

refactor: Wagtail style changes

---

projects/hslayers/src/common/upload/upload.html
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.ts
projects/hslayers/src/components/add-data/file/file.service.ts
projects/hslayers/src/components/add-data/file/types/file-descriptor.type.ts
projects/hslayers/src/components/add-data/vector/vector-data.type.ts
projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts
projects/hslayers/src/components/layermanager/widgets/type-widget.component.html
projects/hslayers/src/components/layout/layout.component.ts
projects/hslayers/src/components/layout/layout.service.ts
projects/hslayers/src/components/styles/styler.component.ts

feat: Allow SLD style for loaded geojson layers + fix sidebar toggleable

---

package-lock.json
projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.spec.ts
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.html
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
projects/hslayers/src/components/save-map/save-map.service.ts

Compositions

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/layman/access-rights/layman-access-rights.html
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.html
projects/hslayers/src/components/styles/styler.component.html

* add missing cs translations
* correct some i18n strings
none

Add & correct translations

---

projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/map/map.service.ts

Composition loading

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts

------------
Handle unsuccessful datasource parsing

refactor: Handle unsuccessful datasource parsing

---

projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
projects/hslayers/src/components/save-map/layman.service.ts

Fixes filip

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.html
projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/common/common.module.ts

- Remove size constraint for SHP uploaded to Layman
- Fix/Add progress bars for tracking - data ziping and uploading
fixes #3181

Shp upload

---

projects/hslayers/src/components/add-data/url/wms/wms.service.ts
projects/hslayers/src/components/language/language.service.ts
projects/hslayers/src/components/layout/dialogs/dialog-container.service.ts
projects/hslayers/src/components/layout/dialogs/dialog-item.ts
projects/hslayers/src/components/layout/layout.service.ts

------------
Added some default "default" app IDs.
relates to #2719

Pre-fill 'default' app where appropriate

---

projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.ts
projects/hslayers/src/components/add-data/file/file-base.component.ts
projects/hslayers/src/components/add-data/file/file.component.html
projects/hslayers/src/components/add-data/file/raster/raster.component.ts
projects/hslayers/src/components/add-data/file/shp/shp.component.ts
projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
projects/hslayers/src/components/add-data/url/add-data-url.component.html
projects/hslayers/src/components/add-data/vector/vector-data.type.ts
projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
projects/hslayers/src/components/add-data/vector/vector-file/vector-file.spec.ts
projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.html
projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts

PR resolves feature request in #3189 issue ticket and implements refactoring requested in #3180 issue ticket.
closes #3189 
closes #3180 

Check if url is obtainable for add-data-vector-url and clean up dataType mess (Issues 3189 and 3180)

---

projects/hslayers/src/assets/locales/sk.json

style(locales): Add missing SK translations

---

projects/hslayers/src/assets/locales/lv.json

Filled in missing Latvian translations for i18n strings.

Added missing LV translations

---

package-lock.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/layermanager/editor/layer-editor.html
projects/hslayers/src/components/layermanager/gallery/basemap-gallery.html
projects/hslayers/src/components/layermanager/gallery/layermanager-gallery.component.ts
projects/hslayers/src/components/layermanager/layermanager.html
projects/hslayers/src/components/query/feature-list/feature-list.component.ts
projects/hslayers/src/components/styles/styler.component.ts
projects/hslayers/src/components/styles/styler.service.ts

Store SLD change per layer + missing SK translations

---

projects/hslayers/src/components/info/partials/info.component.scss
projects/hslayers/src/css/hslayers-bootstrap.scss
projects/hslayers/src/css/hslayers-colors.scss

Please give a short description of the changes you propose. Please use prose and try not to be too technical, if possible. Make sure to mention people that you think should know about the PR.

fix: Map swipe button style

---

.gitignore
projects/hslayers/src/components/compositions/compositions-parser.service.ts

Typo in i18n & .gitignore update

---

cypress/tests/external.cy.ts
projects/hslayers/src/components/external/external.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

* Add new type of domFeatureLink action which selects the feature and opens the info panel with attributes.
* Expand extent of feature when zooming to. The zoom was too close especially for points. 
* Fix querying the feature by its ID

feat: New feature select DOM action

---

.gitignore
cypress.config.ts
cypress/support/e2e.ts
cypress/tests/add-data.cy.ts
package-lock.json
package.json
projects/hslayers/src/components/layout/toast/toast.service.ts
projects/hslayers/src/config.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Add tests for detecting errors to layers rendered on OL canvas

Visual testing

---

projects/hslayers/src/components/draw/draw.service.params.ts
projects/hslayers/src/components/draw/draw.service.ts

- Refactoring for drawing service
- Normalizing drawing interaction functionality to be able to call from outside better

Drawing improvements

---

projects/hslayers/src/components/compositions/compositions-parser.service.ts
projects/hslayers/src/components/compositions/compositions.service.ts
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/core/event-bus.service.ts
projects/hslayers/src/components/info/info.component.ts
projects/hslayers/src/components/layermanager/gallery/basemap-gallery.html
projects/hslayers/src/components/layermanager/gallery/gallery.component.scss
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/map/models/remove-composition-layers-options.ts
projects/hslayers/src/config.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Use map composition as a source for basemaps using 
````
appConfig.base_layers{
url: string, 
default: string, //Base layer which should be visible by default
}
````
- Reload defaultComposition layers on map reset
fixes #3307 

Basemap compo

---

projects/hslayers/src/common/pager/pager.component.html

Fixed pagination disabling
closes #3631 

fix: Properly disable pagination buttons

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/styles/rule/rule.component.html
projects/hslayers/src/components/styles/symbolizers/color-picker/color-picker.component.html
projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/icon-symbolizer/icon-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/icon-symbolizer/icon-symbolizer.component.ts
projects/hslayers/src/components/styles/symbolizers/line-symbolizer/line-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/mark-symbolizer/mark-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/mark-symbolizer/mark-symbolizer.component.ts

Warn user about fill color being ignored when graphic fill is present
fix #3444

Improve graphics fill warnings and button to remove graphic

---

package-lock.json
projects/hslayers/src/components/add-data/url/wms/wms.service.ts

refactor: Get WMS Layer BBox

---

projects/hslayers-server/package-lock.json
projects/hslayers-server/src/layman.js
projects/hslayers-server/src/oauth2/util.js
projects/hslayers-server/src/proxy.js

Fixes error "got is not a function" introduced by #3797
#3797

Fix dynamic import of "got" lib

---

projects/hslayers/src/common/get-capabilities/arcgis-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wfs-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wms-get-capabilities.service.ts
projects/hslayers/src/common/get-capabilities/wmts-get-capabilities.service.ts
projects/hslayers/src/components/add-data/url/add-data-url.service.ts
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts

Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …

Hot fix adddata

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/add-data/vector/vector.service.ts
projects/hslayers/src/components/draw/draw-layer-metadata/draw-layer-metadata.component.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/save-map/layman-utils.ts
projects/hslayers/src/components/styles/styler.component.html
projects/hslayers/src/components/styles/styler.service.ts
projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/mark-symbolizer/mark-symbolizer.component.html
projects/hslayers/src/components/styles/symbolizers/text-symbolizer/text-symbolizer.component.html
projects/hslayers/src/css/hslayers-bootstrap.scss

Update styler component based on new Geostyler changes
-  Use fillOpacity parameter instead of opacity for fill of mark symbolized
-  Remove 'Not visualized correctly' warning from font weight, style of text symbolized and graphicFill of fill Symbolizer
- Update styler UI to indicate that style changes are being saved
#3677 

Geostyler update changes

---

projects/hslayers/src/common/layers/hs.source.SPOI.ts
projects/hslayers/src/common/layers/hs.source.SparqlJson.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Fix multiple falsy assumptions about layers loaded from SPARQL endpoints.
none

Fix GeoSPARQL layers loading

---

projects/hslayers/src/common/layers/hs.source.SPOI.ts
projects/hslayers/src/common/layers/hs.source.SparqlJson.ts

backport of #3993 to 11.2
#3993 

Fix GeoSPARQL layers loading (11.x)

---

projects/hslayers/src/components/compositions/compositions-parser.service.ts

Cannot replicate, but shall be fixed simply by verifying that the function being called exists.
refs #3934

Safely check composition load success

---

projects/hslayers/src/components/layermanager/layermanager.service.ts

fix: Greyscale baselayers on init

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
projects/hslayers/src/components/add-data/catalogue/catalogue-map.service.ts
projects/hslayers/src/components/compositions/compositions-map.service.ts

- pointermove events debounce, unlisten when not necessary
- fix/udpdate for sensors units

Sensors fixes v 11

---

projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts

-----------
Please give a short description of the changes you propose. Please use prose and try not to be too technical, if possible. Make sure to mention people that you think should know about the PR.

Sensors 11

---

projects/hslayers/src/hslayers.layman.interceptor.ts
projects/hslayers/src/hslayers.module.ts

Release 11.x update - Layman proxy URL

---

projects/hslayers/src/components/add-data/catalogue/catalogue-map.service.ts
projects/hslayers/src/components/compositions/compositions-map.service.ts

Debounce listeners, unlisten when not necessary eg. when no or other than compositions/addData panels are open

Pointer move listeners for compositions and adddata catalogues

---

projects/hslayers/src/common/layman/layman-utils.ts
projects/hslayers/src/common/layman/layman.service.ts
projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
projects/hslayers/src/components/add-data/common/common-file.service.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
projects/hslayers/src/components/add-data/vector/vector-descriptors/vector-layer-descriptor.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts
projects/hslayers/src/components/compositions/compositions.component.ts
projects/hslayers/src/components/compositions/compositions.spec.ts
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/draw/draw.service.ts
projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/styles/styler.service.ts
projects/hslayers/test/data/composition.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Always use Layman generated styles with Layman layers (Issue 3946)

---

projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts

Calculate combined ArcGIS service layer extent only from valid extents

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
projects/hslayers-sensors/src/components/sensors/sensors-unit-list-item.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json

- allow comparison of sensors between different sensor units

Sensors update 11x

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
projects/hslayers-sensors/src/components/sensors/sensors-unit-list-item.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json

Not tested on app using develop/v12, build works
closes #4101 

Sensor changes (port from version 11.2)

---

projects/hslayers/src/common/remove-multiple/remove-layer-dialog.component.html
projects/hslayers/src/common/remove-multiple/remove-layer-dialog.component.ts
projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.ts
projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts

Hotfix filip

---

projects/hslayers/src/common/get-capabilities/arcgis-get-capabilities.service.ts
projects/hslayers/src/components/add-data/common/common.component.scss
projects/hslayers/src/components/add-data/common/url/details/details.component.html
projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
projects/hslayers/src/components/add-data/url/types/data-object.type.ts
projects/hslayers/src/components/add-data/url/wms/wms.service.ts
projects/hslayers/src/components/add-data/url/wmts/wmts.service.ts
projects/hslayers/src/components/legend/legend.service.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/query/query-wms.service.ts
projects/hslayers/src/components/utils/utils.service.ts
projects/hslayers/src/components/utils/utils.spec.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Use cached tiles if possible when loading ArcGIS rest service layers
closes #4214

ArcGIS rest tiles

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/get-capabilities/dimension-time.service.ts
projects/hslayers/src/common/get-capabilities/dimension.service.ts
projects/hslayers/src/common/get-capabilities/wms-get-capabilities-response.interface.ts
projects/hslayers/src/common/layer-extensions.ts
projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
projects/hslayers/src/components/add-data/url/wms/wms.service.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts
projects/hslayers/src/components/layermanager/editor/layer-editor.component.ts
projects/hslayers/src/components/layermanager/editor/layer-editor.service.ts
projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
projects/hslayers/src/components/layermanager/layermanager.module.ts
projects/hslayers/src/components/layermanager/layermanager.service.ts
projects/hslayers/src/components/layermanager/widgets/extent-widget/extent-widget.component.html
projects/hslayers/src/components/layermanager/widgets/extent-widget/extent-widget.component.ts
projects/hslayers/src/components/layermanager/widgets/layer-editor-widget-base.component.ts
projects/hslayers/src/components/layermanager/widgets/metadata-widget.component.html
projects/hslayers/src/components/utils/layer-utils.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Add 'Igonre extent' toggle for WMS layers.
closes #4201 

Ignore WMS extent

---

projects/hslayers-cesium/src/hscesium-camera.service.ts
projects/hslayers-cesium/src/hscesium-layers.service.ts
projects/hslayers-cesium/src/hscesium-time.service.ts

------------
Several minor fixes and a bit of clean-up of hslayers-cesium code.
none

Hslayers-cesium fixes

---

projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.ts
projects/hslayers/src/components/layout/dialogs/dialog-container.service.ts
projects/hslayers/src/components/map/map.component.ts
projects/hslayers/src/components/map/map.service.ts
projects/hslayers/src/components/sidebar/sidebar.service.ts

Cleanup components when they are destroyed (issue 4336)

---

projects/hslayers-server/src/proxy.js
projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/pager/pager.component.ts
projects/hslayers/src/components/add-data/catalogue/catalogue.component.html
projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/vector/vector.service.ts
projects/hslayers/src/components/compositions/compositions-list-item.component.html
projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
projects/hslayers/src/components/map-swipe/map-swipe.component.html
projects/hslayers/src/components/map-swipe/map-swipe.component.scss
projects/hslayers/src/components/map-swipe/map-swipe.component.ts
projects/hslayers/src/components/save-map/dialog-result/dialog-result.component.html
projects/hslayers/src/components/save-map/dialog-result/dialog-result.component.ts
projects/hslayers/src/components/save-map/layman.service.ts
projects/hslayers/src/components/save-map/save-map.service.ts
projects/hslayers/src/components/styles/styler.component.html
projects/hslayers/src/components/styles/styler.service.ts

Composition, style related improvements

---

projects/hslayers-sensors/src/components/sensors/partials/sensor-unit.ts
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/types/interval.type.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts

Port v11x hslayers-sensors changes .

Port sensors11x

---

projects/hslayers-sensors/src/components/sensors/partials/sensor-unit.ts
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/types/interval.type.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
projects/hslayers/src/components/query/query-vector.service.ts
projects/hslayers/src/components/styles/filters/add-filter-button.component.ts
projects/hslayers/src/components/styles/filters/filter.type.ts
projects/hslayers/src/components/styles/filters/filters.component.ts
projects/hslayers/src/components/styles/filters/filters.service.ts

Fix failing build as a result of typescript import cycle created in stlyer
https://stackoverflow.com/questions/67539780/one-or-more-import-cycles-would-need-to-be-created-to-compile-this-component-wh

fix: Styler typescript import cycle, Sensors

---

projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
projects/hslayers/src/components/add-data/url/wmts/wmts.service.ts

Missed that layerOptions are optional. Original change errors when not loading from composition.

Hotfix addurl

---

projects/hslayers/src/common/widgets/epsg.pipe.ts
projects/hslayers/src/common/widgets/public-api.ts
projects/hslayers/src/common/widgets/ui-extensions.module.ts
projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
projects/hslayers/src/components/add-data/common/url/details/details.component.html

Add SRS names into the selector
closes #4444

EPSG pipe - make EPSG selection  userfriendly by providing name

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/components/query/query.component.html
projects/hslayers/src/components/save-map/save-map.component.html
projects/hslayers/src/components/sidebar/impressum.component.html
projects/hslayers/src/components/sidebar/impressum.component.scss

Mostly UI polishing:
* Added missing translation "No features selected"
* Smaller logo and less visually dominant impressum
* Hidden empty space in case current-user is obtained via Layman proxy
...see commit messages
none

Pre-release polishing

---

projects/hslayers/src/components/sidebar/sidebar.service.ts
projects/hslayers/src/config.service.ts

Fix sidebar toggleable configuration as sidebar calculation was rewriting the state

fix: Sidebar toggleable

---

projects/hslayers/src/components/add-data/file/raster/raster-timeseries/raster-timeseries.component.html
projects/hslayers/src/components/add-data/file/raster/raster-timeseries/raster-timeseries.component.ts
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.html
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.scss
projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

Replacement of deprecated component-based accordion with a directive. Necessary to support ng-bootstrap 16 and above.
resolves #4253 
updated component in second commit relates to #2836 and #2873

Replace NgbAccordion component with directive

---

projects/hslayers/src/components/core/core.service.ts

fix: Missing WMS query service import preventing it from be used

---

projects/hslayers/src/assets/locales/cs.json
projects/hslayers/src/assets/locales/en.json
projects/hslayers/src/assets/locales/lv.json
projects/hslayers/src/assets/locales/sk.json
projects/hslayers/src/common/layman/dialog-set-permissions/set-permissions.component.html
projects/hslayers/src/common/layman/dialog-set-permissions/set-permissions.component.ts

Saving permissions progress

---

projects/hslayers/src/components/add-data/add-data.component.html
projects/hslayers/src/components/add-data/common/common.service.ts
projects/hslayers/src/components/add-data/common/url/details/details.component.html
projects/hslayers/src/components/add-data/common/url/details/details.component.ts
projects/hslayers/src/components/draw/draw.component.html
projects/hslayers/src/components/draw/draw.component.ts
projects/hslayers/src/components/layout/panels/panel-header/panel-header.component.html
projects/hslayers/src/components/layout/panels/panel-header/panel-header.component.ts

Panel header, WMS settings

---

.github/workflows/build+test_server.yml
projects/hslayers-server/CHANGELOG.md
projects/hslayers-server/package-lock.json
projects/hslayers-server/package.json
projects/hslayers-server/src/proxy.js
projects/hslayers-server/test/proxy.spec.js

Fix GH workflow action, which was testing hslayers library, app and sensors instead of hslayers-server.
Add GitHub Actions reporter for hslayers-server tests (empty output when OK, error log when error occurs).
Update dependencies.
Prepare release hslayers-server@2.0.0
none

Fix server workflow & prepare hslayers-server release

---

projects/hslayers/components/layer-manager/dialogs/remove-all-dialog.component.ts
projects/hslayers/shared/draw/draw.service.ts
projects/hslayers/shared/event-bus/event-bus.service.ts
projects/hslayers/shared/layer-manager/layer-manager.service.ts

refactor(layer-manager): Move remove added layers to the dialog, 

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.module.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts

panel width, imports, mapEventHandlersSet

v14 sensor updates

---

projects/hslayers/services/core/core.service.ts

Show sidebar labels if no mainpanel is selected

fix(sidebar): Show sidebar labels if no mainpanel is selected

---

projects/hslayers-cesium-app/src/app/app.component.ts
projects/hslayers-cesium-app/src/index.html

Please give a short description of the changes you propose. Please use prose and try not to be too technical, if possible. Make sure to mention people that you think should know about the PR.

fix(cesium-app): globFunctions lookup

---

projects/hslayers-cesium/src/hscesium-layers.service.ts
projects/hslayers-cesium/src/hscesium.component.ts
projects/hslayers-cesium/src/hscesium.service.ts

Please give a short description of the changes you propose. Please use prose and try not to be too technical, if possible. Make sure to mention people that you think should know about the PR.

perf(cesium): Reduce usage of some unnecessary cesium sync callbacks

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
projects/hslayers-sensors/src/components/sensors/sensors.component.ts
projects/hslayers-sensors/src/components/sensors/sensors.service.ts

- made `HsMapService` optional. Injection is controlled by `MAPSERVICE_DISABLED˛` injection token provided by container application root module :
```
@NgModule({
...
providers: [{provide: 'MAPSERVICE_DISABLED', useValue: true}],
...
})
```
interaction of lib functionality with map service is then dependent on the existance of the service.
- <ins>primary usage of the lib in simplified mode is via `unit_id` GET  parameter</ins> that will be used to look for sensor unit to be displayd. Without unit_id all unit for the locations would be avilable
Other functionality provided by hslayers is kept either because its necessary or its presnece is not increasing the bundle size significantly nor it adds too much of an overhead.
In addition to the change made here container app has got to kinda …

refactor(sensors): Sensors without map

---

projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
projects/hslayers-sensors/src/components/sensors/sensors.service.ts
projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
projects/hslayers/assets/locales/cs.json
projects/hslayers/assets/locales/en.json
projects/hslayers/assets/locales/sk.json

Template fallback for no unit cases , quicker aggregations

refactor(sensors): Template fallback for no unit cases , quicker aggregations

---

projects/hslayers/components/layer-manager/dimensions/date-preformat.pipe.ts
projects/hslayers/components/layer-manager/dimensions/layer-editor-dimensions.component.ts
projects/hslayers/components/layer-manager/dimensions/layer-manager-time-editor.component.html
projects/hslayers/components/layer-manager/layer-manager.module.ts
projects/hslayers/services/event-bus/event-bus.service.ts
projects/hslayers/services/get-capabilities/dimension-time.service.ts
projects/hslayers/services/layer-manager/layer-manager.service.ts
projects/test-app/src/hslayers-app/hslayers-app.component.ts

- fix race conditions of layerDimensionDefinitionChanges. After mapEventHandlersSet emition layerDescriptors for default_layer should be available and setupTimeLayer should be executed correctly
- Simpify dimensions component value update by merging/debouncing subscribtions of layerDescriptor and layerDimensionDefinitionChanges . Replaced ngOnChange handler as well as I was not really followiing why its necessary (no inputs)
fixes #5059 

WMS-T dimensions not loading

---

projects/hslayers/common/clipboard-text/clipboard-text.component.ts
projects/hslayers/common/clipboard-text/index.ts
projects/hslayers/common/clipboard-text/ng-package.json
projects/hslayers/common/clipboard-text/public-api.ts
projects/hslayers/common/widgets/recursive-dd.component.html
projects/hslayers/common/widgets/recursive-dd.component.ts
projects/hslayers/components/compositions/compositions.module.ts
projects/hslayers/components/compositions/dialogs/info-dialog.component.html
projects/hslayers/components/compositions/dialogs/share-dialog.component.html
projects/hslayers/components/layer-manager/layer-manager.module.ts
projects/hslayers/components/layer-manager/widgets/type-widget.component.html
projects/hslayers/components/layer-manager/widgets/type-widget.component.ts

Reusable UI component for 'Copyable text'  - plain text or hyperlink

Clipboard text component

---

.github/workflows/build+test_libs_apps.yml
.github/workflows/build+test_server.yml
projects/hslayers-server/package-lock.json
projects/hslayers-server/package.json
projects/hslayers-server/server.js

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with
https://stackoverflow.com/questions/78876691/syntaxerror-unexpected-identifier-assert-on-json-import-in-node-v22
Minimum required Node version increased to 18.20 or 20.10.
Increased Node version in CI to 22. Now we test v18 and v22 (oldest maintained and current).
closes #5413 

Switch from "assert" to import attributes

---

projects/hslayers/components/draw/draw-edit/draw-edit.component.ts
projects/hslayers/components/query/query-wms.service.ts
projects/hslayers/components/query/query.component.html
projects/hslayers/components/query/query.component.ts
projects/hslayers/services/query/query-base.service.ts
projects/hslayers/services/query/query-vector.service.ts

- A silent issue was causing incorrect features being removed from the feature query list (found out while specifying the types...).
- Missing types has been defined or redefined.
none

Define query types & fix feature deletion

---

projects/hslayers/config/config.service.ts
projects/hslayers/test/config.service.mock.ts
projects/hslayers/test/config.service.spec.ts

- gracefully handle config update errors
- add tests
fixes #5495 

fix(config): Prevent crash on config update errors

---

projects/hslayers/services/add-data/common-file.service.ts

Display proper error message in add-data
#5637

Display proper error message in add-data

---

projects/hslayers/assets/locales/cs.json
projects/hslayers/assets/locales/en.json
projects/hslayers/assets/locales/lv.json
projects/hslayers/assets/locales/sk.json
projects/hslayers/common/layman/access-rights/layman-access-rights.component.html
projects/hslayers/common/layman/access-rights/layman-access-rights.component.ts
projects/hslayers/test/access-rights/layman-access-rights.component.spec.ts

- updates to access right granting:
- use EVERYONE instead of idividual user names when applicable
- Handle no roles more user-friendly
fixes #5753 

Permissions update
