hslayers/hslayers-ng

- .gitignore
- components/core/core.js
- components/routing/routing.js
- examples/routing/hslayers.js
- examples/routing/index.html
@wohnout: At your convenience, review and merge.
- Added s4a to root require.js configuration
- Added s4a as dependency for routing.js scrip of routing module
- Added shim definition to hslayers.js config of specific example (to avoid loading it for all apps based on HSLayers NG)
- Removed manual load of library from routing example index.html
> Modified to use s4a.js via require shim

- components/hscesium/hs_cesium_layers.js
Wrong access token was used, if terrain providers are defined in app.js,
because token is set inside hscesium.js module, which is used later.
Now the createWorldTerrain function will be called,
when the layer is turned on and thus the correct token will be used.
fixes #147
> Access token usage fixed for cesium terrain layers.

- wiki/config.txt
Add information about 'hostname' objects to the 'config' wiki.
Closes #161
> Describe the purpose of 'hostname' objects

- .eslintrc.json
We use these two rules completely differently in our current codebase, but it's already unified, so no need to change our customs.
> Change angular/di and import/extensions ESLint rules

- components/layout/layout.service.js
This fix returns backwards compatibility with
config.locationButtonVisible parameter
closes #611
> Fix crash with deprecated config

- components/core/core.service.js
- components/search/partials/searchinput.html
- components/search/search.controller.js
- components/sidebar/partials/sidebar.html
- Scaling bug of app (iPhones only) after portrait -> landscape -> portrait rotation. State as seen in the picture bellow actually consists of two problem. Vertical shift of the conent is caused by bug descirbed here:
https://forums.macrumors.com/threads/is-this-a-mobile-safari-bug-white-space-appears-at-bottom-after-rotating-iphone.2209551/ Used proposed solution ( n. 13). 
Horizontal shift is caused by content overflowing to the side after the rotation, can be fixed by adding 'overflow:hidden' to #hs-app element.
- Also changed sidebar toggle icon and after @fzadrazil's suggestion made search icon always visible
> App dimensions for iPhone

- index.js
- package-lock.json
- package.json
- scripts/webpack.common.js
HSL_PATH variable can be used to control it. If its not set
./node_modules/hslayers-ng/dist/ will be used by default.
Lazy loading path problem was described in https://github.com/webpack/webpack/issues/7968
https://github.com/agoldis/webpack-require-from
https://github.com/webpack/webpack/issues/7077#issuecomment-383029585
but https://github.com/inferpse/dynamic-pub-path-plugin/blob/master/index.js
can be used for that.
fixes #664
> Dynamically set publicPath in webpack lazy loading

- components/map/map.controller.js
Fixes attempt to read empty URL parametre
Solves #688
> Fix empty getParamValue()

- .editorconfig
- .eslintrc.json
- package-lock.json
- package.json
These changes allow using ESLint for TypeScript files along with JavaScript files.
It also adds .editorconfig, which should enforce our white-space rules also in the time of file creation.
> ESLint update with TS

- .eslintrc.json
TypeScript rules now have priority over OpenLayers/Prettier rules.
Discourage usage of angular.isDefined/Undefined.
Fixes #791
> Update ESLint rules

- components/core/core.service.ts
- components/layermanager/dimensions/layer-editor-dimensions.component.ts
- components/layermanager/layermanager.component.ts
- components/layermanager/partials/layermanager.html
* Fix Layer Manager undefined error
* Fix un/hiding "Others" layers
* Fix isAuthorized() return value
I would especially welcome a review of the last commit (fa89b2f). I came across this and it just seemed wrong, but maybe there was some intention behind the scenes. But a function which always returns 'true' seems useless to me.
> Layer Manager fixes

- components/datasource-selector/datasource-selector.service.js
datasourcePaging.loaded is always defined -> filter by its value instead
Well, that was a huge code change 😄 
Disclaimer: I do not fully understand the behaviour behind it and why this filter was set the way it was. Hence, this change may introduce some other bugs elsewhere...
fixes #1089
> Don't filter endpoints by datasourcePaging.loaded

- components/add-layers/vector/add-layers-vector.module.ts
- components/add-layers/vector/add-layers-vector.service.js
- components/add-layers/vector/add-layers-vector.spec.ts
- components/compositions/compositions.component.js
- components/compositions/compositions.module.ts
- components/compositions/compositions.spec.ts
- components/compositions/layer-parser.service.js
- components/styles/styler.service.ts
The problem with map integration was that we have in composition
```
'layers': [
{
'metadata': {},
'visibility': true,
'opacity': 1,
'title': 'Measurement sketches',
'className': 'Vector',
'features': '{"type":"FeatureCollection","features":[]}',
'maxResolution': null,
'minResolution': 0,
'projection': 'epsg:4326',
'style': {
'fill': 'rgba(255, 255, 255, 0.2)',
'stroke': {'color': '#ffcc33', 'width': 2},
},
},
```
and the style property is being passed to OL layer constructor as is instead of being parsed and converted to openlayers Style object resulting in 
```
ERROR Error: Uncaught (in promise): AssertionError: Assertion failed. See https://openlayers.org/en/v6.4.3/doc/errors/#41 for details.
AssertionError: Assertion failed. See https://openlayers.org/en/v6.4.3/doc/errors/#41 for …
```
> Error for whiteboard composition with layer style loading 

- components/layermanager/layer-editor-vector-layer.service.ts
- components/save-map/layer-synchronizer.service.ts
- components/save-map/layman.service.ts
Multiple problems are fixed here:
* Layer description (wfs, wms endpoint urls) were first retrieved for anonymous (browser) user, cached and on subsequent requests wrongly used even after user authorizes resulting in:
"https://groundwater.smartagro.lv/layman/client/geoserver/browser/wfs"
where it should have been 
"https://groundwater.smartagro.lv/layman/client/geoserver/test/wfs"
* Too many current-user requests to layman get issued for each synchronized layer
* 'events-suspended' attribute could be set in uick succession multiple in async function, hich could result in addfeature/changefeature events executed when they are actually pulled from layman, not drawn by user.
> Fix layman sync problems

- common/arcgis/get-capabilities.service.js
- common/layman/layman-current-user.component.js
- common/layman/layman-login.component.js
- common/layman/layman.service.js
- common/wfs/get-capabilities.service.js
- common/wms/get-capabilities.service.js
- common/wmts/get-capabilities.service.js
- components/add-layers/vector/VectorLayerDescriptor.js
- components/add-layers/vector/add-layers-vector.service.js
- components/add-layers/wfs/add-layers-wfs.component.js
- components/compositions/compositions-parser.service.js
- components/compositions/endpoints/compositions-layman.service.js
- components/compositions/layer-parser.service.js
- components/draw/draw-layer-metadata.component.js
- components/draw/draw.controller.js
- components/draw/draw.service.js
- components/hscesium/cesium-layers.service.js
- components/hscesium/cesium.service.js
- components/layermanager/layermanager-layerlist.directive.js
- components/layermanager/layermanager.service.js
- components/map/map.service.js
- components/query/query-base.service.js
- components/save-map/layer-synchronizer.service.js
- components/save-map/layman.service.js
- components/save-map/save-map.service.js
- backport layman sync fixes
- Update wfsTrasnsaction url according to new layman WFS proxy
- store synchronize parameter to cookies so after a reload layer is synced with layman once again automaticaly
> Fixes 1.25

- components/query/partials/feature-popup.html
- components/query/partials/infopopup.html
- components/query/query-base.service.ts
Port of #1250 into current develop + one tiny UI improvement
Before:
After:
(not the "_Untitled feature_", but the close icon)
> Fix issue 1249: Pop-up window disappearing (develop)

- components/add-layers/drag-drop-layer.service.ts
- components/add-layers/shp/add-layers-shp.component.ts
- components/add-layers/shp/add-layers-shp.service.ts
- components/add-layers/shp/file-descriptor.ts
- components/add-layers/vector/VectorLayerDescriptor.ts
- components/add-layers/vector/VectorSourceFromUrl.ts
- components/add-layers/vector/add-layers-vector-url-parser.service.ts
- components/add-layers/vector/add-layers-vector.component.ts
- components/add-layers/vector/add-layers-vector.service.ts
- components/add-layers/vector/add-vector-layer.directive.html
- components/add-layers/vector/vector-source-descriptor.ts
- components/compositions/compositions-parser.service.ts
- components/compositions/compositions.service.ts
- components/compositions/endpoints/compositions-layman.service.ts
- components/compositions/endpoints/compositions-micka.service.ts
- components/compositions/endpoints/compositions-status-manager.service.ts
- components/compositions/layer-parser/layer-parser.service.ts
- components/datasource-selector/datasource-selector.service.ts
- components/datasource-selector/layman/layman.service.ts
- components/datasource-selector/micka/micka.service.ts
- components/datasource-selector/select-type-to-add-layer-dialog.component.ts
- components/layermanager/layer-editor.sub-layer-checkboxes.component.ts
- components/layermanager/layermanager-metadata.service.ts
- components/layermanager/layermanager.service.ts
- components/layermanager/partials/sub-layer-checkboxes.html
- components/save-map/layman.service.ts
- components/save-map/partials/panel.html
- components/save-map/save-map-simple-form.component.ts
- css/app.scss
- Implement support for .wmc compositions
- Use both name and title correctly when loading layers from layman
- Fix saving title to layman incorrectly
- Unsubscribe from src changes after view fitted after layer is laoded from layman 
- Parse maxScaleDenominator into maxResoluion param 
- Display grayed layer name if layer out of the scale or switched off
- Create sublayers WMS layer config param. Adding layer name to this parameter makes it sublayer of the layer and parses avalaible information form getCapabilities. In constrast with the params.LAYERS it doesnt create additional sublayer structure even if its available. Currently no additional nested sublayers are possible with this param
> Port 1.26changes

- components/add-layers/add-layers.component.js
- components/add-layers/wfs/add-layers-wfs-service.js
- components/add-layers/wfs/add-layers-wfs.component.js
- components/add-layers/wms/add-layers-wms.component.js
- components/add-layers/wms/add-layers-wms.service.js
- components/layermanager/layermanager-metadata.service.js
Can be used like this: <s>http://localhost:8080/?wms_to_connect=https://hub.lesprojekt.cz/client/geoserver/viktorie_sloupova/ows&visible_layers=af_suicide_rate</s>
New implementation is following:
localhost:8080/?wms_to_connect=https://hub.lesprojekt.cz/client/geoserver/viktorie_sloupova/ows&wms_layers=africa_driving_side
or
localhost:8080/?wfs_to_connect=https://hub.lesprojekt.cz/client/geoserver/viktorie_sloupova/wfs&wfs_layers=af_suicide_rate
respectively.
Advantage: It does not override `visible_layers` property, hence it does not disable basemaps if they were turned on by other means.
fixes #1176
> Parse WMS or WFS layer from the URL parametres

- components/compositions/compositions-parser.service.js
- components/compositions/compositions.service.js
- components/draw/draw.controller.js
Improves the loading of compositions from URL param so additionally to this
http://localhost:8080/?composition=https://hub.lesprojekt.cz/rest/vacha/maps/co_ja_vim/file
we now also load from this
http://localhost:8080/?composition=https://hub.lesprojekt.cz/rest/vacha/maps/co_ja_vim
and also if the URL is malformed, a proper error message is displayed to the user (instead of just error raising in the console).
fixes #1178
> Load composition also from Layman URL

- .release-it.json
- package.json
Run build after the version bump so the correct version is displayed in the sidebar
> Update release process

- package.json
One tiny change to make the release in NPM a bit smaller.
/po directory was superseded by /assets/locales
bootstrap-isolate.js was superseded by SASS
> Remove /po and bootstrap-isolate from NPM files

- components/map/map.service.ts
Prevents layers from getting under the base map on permalink layer load. Should be enough to fix #1390
> Dont re-add baselayers

- components/save-map/layman.service.ts
- Not possible to upload new layer to layman.
When layer was not found on Layman, server responded with code 404 which needs to be handled inside catch block. Maybe some change on layman side after the update
> Handle 404 in describeLayer properly

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/components/add-layers/add-layers.service.ts
- projects/hslayers/src/components/add-layers/common/add-layers-target-position.component.html
- projects/hslayers/src/components/add-layers/common/add-layers-target-position.component.ts
- projects/hslayers/src/components/add-layers/shp/add-layers-shp.component.ts
- projects/hslayers/src/components/add-layers/vector/add-layers-vector.component.ts
- projects/hslayers/src/components/add-layers/vector/add-layers-vector.service.ts
- projects/hslayers/src/components/add-layers/vector/add-vector-layer.directive.html
- projects/hslayers/src/components/add-layers/wms/add-layers-wms.service.ts
- projects/hslayers/src/components/add-layers/wms/add-wms-layer.directive.html
- projects/hslayers/src/components/compositions/compositions.spec.ts
- projects/hslayers/src/components/core/event-bus.service.ts
- projects/hslayers/src/components/layermanager/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/layer-editor.spec.ts
- projects/hslayers/src/components/layermanager/layer-list.spec.ts
- projects/hslayers/src/components/layermanager/layermanager-layerlist.component.ts
- projects/hslayers/src/components/layermanager/layermanager-physical-layerlist.component.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/layermanager/partials/physical-layerlist.html
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/hslayers.component.spec.ts
Optimized layer sorting, but found out a new bug! Adding layer from external data without providing folder, creates two lists of the same layers array.
P.s. ignore the numbers in the titles.
> Issue 1415/layers sorted to much

- components/map/map.service.js
- components/map/map.service.spec.js
I was unsure about the implementation changes in #1393 so I have threw together a straightforward unit test for the `layersEqual()` function.
I guess it will make no harm to have it included in our code once it's already written 🙂
> Add unit test of map service (1.27)

- components/save-map/save-map.service.js
This PR makes saving layer list to localStorage ("cookies") settable via "saveMapStateOnReload" config option.
> Layer cookies optional (1.27)

- .release-it.json
- package.json
Run build after the version bump so the correct version is displayed in the sidebar
backport of #1368
> Update release process (1.27)

- projects/hslayers/src/hslayers.component.ts
`<hslayers [config]="mapConfig"></hslayers>`
```
export class AppComponent {
mapConfig: HsConfig = {
assetsPath: 'assets/hslayers-ng',
proxyPrefix: window.location.hostname.includes('localhost')
? `${window.location.protocol}//${window.location.hostname}:8085/`
: '/proxy/',
popUpDisplay: 'click',
open_lm_after_comp_loaded: true,
...
```
Examples branch https://github.com/hslayers/examples/tree/issue-1486/config-attribute
examples/full has the implementation
> Ability to set Hslayers config through attribute

- projects/hslayers/src/components/layermanager/layermanager-wmst.service.ts
This PR is consecutive to #1597 and re-implements the possibility to use layers with time-points defined with Duration ISO string (like "1999-01-22T19:00:00/2018-01-22T13:00:00/PT8766H") in the new time-editor.
Layer on the screenshot is "srazky_l_2000_2018_r" from "https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/maps/m_liberec.map".
> Enhance capability of time-editor

- components/print/partials/printdialog.html
> Fix forgotten AngularJS syntax (2.5)

- projects/hslayers/src/components/compositions/compositions.spec.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/hslayers/test/data/composition.js
This is needed when saving/loading compositions because storing as string is inneficient, needs
parsing, adds escape characters and makes harder to read.
fix #1398
> fix: Encode features as Json object instead of string

- .github/workflows/nodejs.yml
Node 10 goes end-of-life. Node 12 is the oldest maintained version from now on.
https://nodejs.org/en/about/releases/
> ci: Bump NodeJS to 12.x

- projects/hslayers/src/components/core/event-bus.service.ts
- projects/hslayers/src/components/info/info.component.ts
- projects/hslayers/src/components/layermanager/layer-descriptor.interface.ts
- projects/hslayers/src/components/layermanager/layermanager-layerlist.component.ts
- projects/hslayers/src/components/layermanager/layermanager.component.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/layermanager/partials/layerlist.html
- projects/hslayers/src/components/layermanager/partials/layermanager.html
- projects/hslayers/src/components/utils/layer-utils.service.ts
- projects/hslayers/src/components/utils/layer-utils.spec.ts
Was rewriting also the way how loading errors and load progress is tracked, to move away from storing those in OL source/layer, but our wrappers instead, similar as Jan did for dimensions.
> Issue 453/layer loading bar

- package.json
- projects/hslayers/src/common/layman/layman-current-user.component.ts
- projects/hslayers/src/common/layman/layman-current-user.html
There happened to be a flawed url (without the query part) on the Login button in some cases which caused the map to reload once the user clicked on Login.
> fix: Set always correct url to the Layman login button

- projects/hslayers/src/components/core/core.service.ts
- projects/hslayers/src/config.service.ts
HsConfig enabledLanguages can be set as string from any container app. User must input required languages code name, such as, LV for latvian. Each code must be sepperated using comma.
Example:
enabledLanguages: 'lv, cs, sk',
> feature: Locales in languages panel can be configured

- projects/hslayers/src/common/layers/hs.source.SPOI.ts
- projects/hslayers/src/common/layers/hs.source.SparqlJson.ts
- projects/hslayers/src/public-api.ts
As this PR contains a port of a previously fixed performance issue (#1648) I would welcome if we can incorporate it into the 4.0 release.
Changes:
- in SparqlJson it is mainly refactoring
- new class hs.source.SPOI which simplifies the usage of SPOI data drastically. Similar source classes can be created in the future for other endpoints as well (not necessarily only SPARQL ones, we can pre-define Layman or Micka sources for example).
> Enhance usability of SPARQL sources

- projects/hslayers/src/common/layman/access-rights/layman-access-rights.component.ts
- projects/hslayers/src/common/layman/access-rights/layman-access-rights.html
- projects/hslayers/src/common/layman/layman.module.ts
- projects/hslayers/src/components/add-data/common/access-rights.interface.ts
- projects/hslayers/src/components/add-data/file/shp/add-data-file-layer.directive.html
- projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.component.ts
- projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.module.ts
- projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.service.ts
- projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts
- projects/hslayers/src/components/add-data/vector/add-data-vector.directive.html
- projects/hslayers/src/components/add-data/vector/add-data-vector.module.ts
- projects/hslayers/src/components/draw/draw-layer-metadata.component.ts
- projects/hslayers/src/components/draw/partials/draw-layer-metadata.html
- projects/hslayers/src/components/save-map/layman.service.ts
- projects/hslayers/src/components/save-map/partials/form.html
- projects/hslayers/src/components/save-map/save-map-advanced-form.component.ts
- projects/hslayers/src/components/save-map/save-map-manager.service.ts
Make sure user can subimt only logicaly valid combination of access rights and unify this behavior acros the library
fixes:#1842
> fix: Send correct access rights parameters to layman

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/legend/legend.service.ts
Useful when automatic legend does not represent the map naturally, like in the rural-attractiveness apps.
I wanted to implement this before (in #1702) but forgot to finish it. Hence this PR is more than simple.
> Allow to disable automatic legend

- projects/hslayers/src/components/layermanager/partials/sub-layer-checkboxes.html
A very streamline fix. There was no other class bound when the `expanded` property was set to `false`, so this change simplifies it a bit.
Other places where the 'show' class occurs are worth the check.
fixes #1873
> Fix sublayers toggle

- projects/hslayers/src/common/history-list/history-list.service.ts
@jmacura Would appreciate if You could try to test if the values null or undefined still pops up in the history list dropdown.
This fix does not guaranty that it will work, but at least could be a starting point.
> Potential fix - do not  add null or undefined url to history list

- projects/hslayers/src/components/compositions/dialogs/dialog_info.html
- projects/hslayers/src/components/compositions/dialogs/info-dialog.component.ts
- projects/hslayers/src/config.service.ts
I claimed this issue.
Works nice for me. The default icon set can be extended by developer-user like so:
```
this.HsConfig.update({
symbolizerIcons: [
{name: 'aerialway', url: 'https://raw.githubusercontent.com/mapbox/maki/main/icons/aerialway.svg'},
{name: 'home', url: 'https://raw.githubusercontent.com/mapbox/maki/main/icons/home.svg'}
],
})
```
with a result like 
closes #1982
> Fix missing icons

- projects/hslayers/src/components/styles/symbolizers/mark-symbolizer.html
Adding the warning signs to MarkerSymbolizer too, as it does not visualize the opacity slider value. Currently only IconSymbolizer can handle it.
refs #1956 (but does not closes it!)
> Add warning to unsupported sliders in geostyler

- package.json
- projects/hslayers/package.json
This is temporarily preserving from upgrade to @openlayers >= 6.6, as it is creating a throng of errors during build.
> Stick ol to version 6.5 for a while

- projects/hslayers/src/components/map/map.service.ts
We are cloning the view passed in configuration so it alsways uses the OL from hslayers and not some
other external OL. In this cloning process all options should be passed along, not just selected
few.
fix #2034
> fix: Pass all view options when cloning the view

- projects/hslayers-app/src/hslayers-app/hslayers-app.component.ts
The 1st commit is an initial attempt to fix styler behaviour in the hslayers-app (follow-up to #1983 and replacement for #1984).
~So far the icons are properly loaded in the modal dialog, but cannot be assigned to the features in the map... Help wanted.~
As @raitisbe resolved, the consecutive problem was not related to the code itself, but rather to the server config. So the issue is resolved by the 1st commit.
> Styler fixes

- projects/hslayers/src/components/query/attribute-row.component.ts
- projects/hslayers/src/components/query/partials/attribute-row.html
- projects/hslayers/src/components/trip_planner/trip-planner.service.ts
This is a fast variant of solving the issue. In the future will consider creating a dropdown attribute rows, in case of more complex features.
refs #2055 
> Issue 2055/attribute values

- projects/hslayers/src/components/draw/draw.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
- projects/hslayers/src/components/styles/styles.ts
When layers are defined in HsConfig without any style or SLD default OL style is used, but SLD was
not generated from that. This commit fills the SLD attribute with a hardcoded xml very similar to
default OL style. This generated SLD can later be used when the layer is clustered. In that case there will be a SLD which to add new filters to, which check if the feature is single or a merged collection of features.
#2052 
> Issue 2052/default old style cluster

- projects/hslayers/src/components/add-data/url/add-data-url.service.ts
- projects/hslayers/src/components/add-data/url/wms/add-data-url-wms.service.ts
The aim of this PR is to pass SLD from file specified in Laymans WFS service metadata to a layer attribute.
In order to do it, capabilities retrieval needs to be refactored and simplified using Promises.
Breaking change:
HsEventBusService.owsCapabilitiesReceived Subject is removed and `requestGetCapabilities` methods to query capabilities in 
* HsWmtsGetCapabilitiesService
* HsArcgissGetCapabilitiesService 
* HsWmsGetCapabilitiesService
* HsWfsGetCapabilitiesService
are renamed to `request` and now return a promise with object `{response: any; error: boolean}`.
#2046 
> Issue 2046/sld wfs

- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/common/download/download.directive.ts
- projects/hslayers/src/common/download/download.module.ts
- projects/hslayers/src/common/upload/file-drop.directive.ts
- projects/hslayers/src/common/upload/upload.component.ts
- projects/hslayers/src/common/upload/upload.html
- projects/hslayers/src/common/upload/upload.module.ts
- projects/hslayers/src/common/widgets/ui-extensions.module.ts
- projects/hslayers/src/components/add-data/common/add-data-common.module.ts
- projects/hslayers/src/components/add-data/file/shp/add-data-file-layer.directive.html
- projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.component.ts
- projects/hslayers/src/components/add-data/file/shp/add-data-file-shp.module.ts
- projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts
- projects/hslayers/src/components/add-data/vector/add-data-vector.directive.html
- projects/hslayers/src/components/add-data/vector/add-data-vector.module.ts
- projects/hslayers/src/components/query/feature.component.ts
- projects/hslayers/src/components/query/partials/feature.html
- projects/hslayers/src/components/query/query-vector.service.ts
- projects/hslayers/src/components/query/query.module.ts
- projects/hslayers/src/components/styles/styler.component.ts
- projects/hslayers/src/components/styles/styler.html
- projects/hslayers/src/components/styles/styler.service.ts
- projects/hslayers/src/components/styles/styler.spec.ts
- projects/hslayers/src/components/styles/styles.module.ts
- projects/hslayers/src/components/styles/symbolizers/icon-symbolizer.html
- projects/hslayers/src/components/styles/symbolizers/text-symbolizer.html
- projects/hslayers/src/public-api.ts
This PR does several things:
+ Extracts upload file picker / drop zone into separate reusable component which now is used to upload SHP, Geojson, KML and SLD for shapefiles
+ Provides uploading of SLD file in Styler panel for all existing vector layers
+ Refactors existing dynamic generation of downloadable content functionality into a directive, to which a string is given as input and event is emited back with a sanitized href attribute content
+ Provides download button for SLD style in styler panel
#2046 
> Download and upload of SLD files for existing vector layers

- projects/hslayers/src/components/query/feature-popup.component.ts
- projects/hslayers/src/components/query/partials/feature-popup.html
- projects/hslayers/src/components/query/query-base.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
- fix: popUp attributes not visible
- Dont store popUp attributes in feature object
- [x ] No
> fix: popUp attributes not visible

- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/components/query/feature-popup.component.ts
- projects/hslayers/src/components/sidebar/partials/sidebar.html
There shouldn't be a hardcoded English text that is being displayed for feature popup.  
> refactor(feature-popup): All displayed text should be translatable

- angular.json
- package.json
HMR didnt realy work because --hmr flag was missing and NG 12 serves application close to production mode with optimization option enabled which makes HMR slow (https://stackoverflow.com/questions/67598130/angular-12-ng-serve-builds-apps-slowly-almost-like-production-builds)
-
> perf: fix HMR and improve recompiling test app

- projects/hslayers/src/components/save-map/partials/form.html
- projects/hslayers/src/components/save-map/partials/panel.html
Removed href attribute from save-map nav items
fixes #2162 
> fix: Context or Author tabs refresh the page

- projects/hslayers/src/components/legend/legend.component.ts
Fixes: Legend not updating after layer is removed.
closes #2213 
> fix(legend): Legend doesn't refresh

- projects/hslayers/src/components/add-data/url/add-data-url.component.html
- projects/hslayers/src/components/add-data/vector/add-data-vector.component.ts
- projects/hslayers/src/components/add-data/vector/add-data-vector.spec.ts
------------
Select data type when adding GeoJSON or KML using url (when adding file directly type needs to stay empty in order to coply with [default ](https://github.com/hslayers/hslayers-ng/blob/ab78f6e315d5b670fc5f6bae287d7cadacc106cd/projects/hslayers/src/components/add-data/vector/vector-descriptors/vector-source-descriptor.ts#L78)case)
fixes #2169 
> fix: Set correct add url vector type

- projects/hslayers/src/components/layermanager/layer-editor.service.ts
- projects/hslayers/src/components/legend/legend-descriptor.interface.ts
- projects/hslayers/src/components/legend/legend-layer/legend-layer.component.html
- projects/hslayers/src/components/legend/legend-layer/legend-layer.component.ts
- projects/hslayers/src/components/legend/legend-layer/legend-layer.spec.ts
- projects/hslayers/src/components/legend/legend.component.ts
- projects/hslayers/src/components/legend/legend.service.ts
- projects/hslayers/src/components/legend/legend.spec.ts
When toggling layer editors without closing previous, the auto legend does not dispaly correct legend.
This PR fixes it.
closes #2232 
> fix(legend): Show correct legend for layer-editor window

- projects/hslayers/src/components/layout/layout.service.ts
- projects/hslayers/src/hslayers.component.ts
Check if hslayers component has already been initialized once, if this is not checked, for map-Whiteboard application, each time the user loads new map composition, all of the panels gets multiplied.
None
> fix: Check if hslayers component, has initialized already

- .gitignore
- projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
- projects/hslayers/src/components/add-data/url/wfs/add-data-url-wfs.service.ts
- projects/hslayers/src/components/layermanager/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/layermanager/partials/layer-editor.html
- projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
- projects/hslayers/src/components/save-map/layman.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
- projects/hslayers/src/components/styles/styles.ts
Check if style file returnerd by Layman contains StyledLayerDescriptor before trying to parse the SLD. The style might have been encoded in QML
#2256 
> fix: Parse SLD only when not qgis style provided

- projects/hslayers/src/components/add-data/common/url/details/details.component.html
- projects/hslayers/src/components/add-data/common/url/nested-layers-table/nested-layers-table.component.html
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/layermanager/editor/sub-layer-checkboxes.html
- projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/layermanager/widgets/scale-widget.component.ts
- projects/hslayers/src/components/utils/layer-utils.service.ts
- projects/hslayers/src/components/utils/layer-utils.spec.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
- projects/hslayers/src/css/hslayers-colors.scss
- projects/hslayers/src/css/hslayers-wo-bootstrap.scss
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Up until now we were incorrectly assigning web service scale denominators to layer resolution parameters which were causing service layers to not render correctly (in relation to map scale). Wrong values were also stored to layer composition object. 
+few smaller changes to UI that gets vroken by liefary css
+consider crs-84 a valid CRS...@fzadrazil  wanted to use it on hub.sieusoil. Any ideas why we were filtering it out?
>  Use layer max/minResolution and service scaleDenominators properly

- projects/hslayers-cesium/src/query-popup.service.ts
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/layout/panels/panel-container.service.interface.ts
- projects/hslayers/src/components/layout/panels/panel-container.service.ts
- projects/hslayers/src/components/query/query-popup-base.service.ts
- projects/hslayers/src/components/query/query-popup-widget-container.service.ts
- projects/hslayers/src/components/query/query-popup.service.model.ts
- projects/hslayers/src/components/query/query-popup.service.ts
- projects/hslayers/src/components/query/query-popup/query-popup.component.html
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/hslayers.component.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Make the HsConfig.queryPopupWidgets overridable by layers property  
```
popUp: {
widgets: ['layer-name', 'clear-layer'],
},
```
#2336 
> Overridable popup widget list

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/query/public-api.ts
- projects/hslayers/src/components/query/query-popup-base.service.ts
- projects/hslayers/src/components/query/query-popup-widget-container.service.ts
- projects/hslayers/src/components/query/query-popup/query-popup.component.html
- projects/hslayers/src/components/query/query.module.ts
- projects/hslayers/src/components/query/widgets/dynamic-text.component.html
- projects/hslayers/src/components/query/widgets/dynamic-text.component.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Override the hover popups content (widgets) with a content generated by a function provided by user
in HsConfig layer definition. The function receives a feature object as a parameter.
fix #2370
> Widget to generate popup content dynamically

- package-lock.json
- package.json
- projects/hslayers/src/common/layman/layman.service.ts
- projects/hslayers/src/components/add-data/add-data.service.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.spec.ts
- projects/hslayers/src/components/draw/draw.service.ts
- projects/hslayers/src/components/draw/draw.spec.ts
- projects/hslayers/src/components/save-map/layman.spec.ts
- projects/hslayers/src/components/save-map/save-map.component.ts
This is needed for components to update the ui and also data, when LAyman responds with code 32: token not active. 
This might not be the best solution, byut using authChage triggers somekind of loop, that I couldn't fix. Feel free to comment or replace this PR.
None
> Broadcast event when user layman session has expired

- package-lock.json
- package.json
- projects/hslayers-server/package-lock.json
- projects/hslayers/README.md
- projects/hslayers/package.json
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/add-data/add-data.service.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/add-data/catalogue/layer-descriptor.model.ts
- projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/url/add-data-url-base.component.ts
- projects/hslayers/src/components/add-data/url/add-data-url.component.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/types/layer-options.type.ts
- projects/hslayers/src/components/add-data/url/types/recursive-options.type.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
- projects/hslayers/src/components/core/event-bus.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
Layman layers having QGIS style instead of SLD should still load the style using
geostyler-qgis-parser
BREAKING CHANGE: Add geostyler-qgis-parser peerdependency: `npm i geostyler-qgis-parser`
fix #2361
> feat: Add QML support for layer styles when loading

- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/add-data/common/common.service.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts-service.ts
Layers from add data are no longer getting loaded by accident. Made some fixes for wfs layer loading as well.
Add data panel gets reset to catalogue view after layers are added.
Closes #2418 
> Fix accidentaly added layers (issue 2418)

- projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.html
- projects/hslayers/src/common/confirm/confirm-dialog.html
- projects/hslayers/src/common/layman/layman-login.html
- projects/hslayers/src/components/add-data/catalogue/catalogue-metadata/catalogue-metadata.component.html
- projects/hslayers/src/components/add-data/common/capabilities-error-dialog/capabilities-error-dialog.component.html
- projects/hslayers/src/components/compositions/dialogs/dialog_delete.html
- projects/hslayers/src/components/compositions/dialogs/dialog_info.html
- projects/hslayers/src/components/compositions/dialogs/dialog_overwriteconfirm.html
- projects/hslayers/src/components/compositions/dialogs/dialog_share.html
- projects/hslayers/src/components/compositions/dialogs/dialog_warning.html
- projects/hslayers/src/components/draw/draw-layer-metadata/draw-layer-metadata.html
- projects/hslayers/src/components/layermanager/dialogs/dialog_remove_layer.html
- projects/hslayers/src/components/layermanager/dialogs/dialog_removeall.html
- projects/hslayers/src/components/save-map/partials/dialog_result.html
- projects/hslayers/src/components/save-map/partials/dialog_save.html
- projects/hslayers/src/components/styles/styler.component.html
- projects/hslayers/src/components/styles/symbolizers/select-icon-dialog/select-icon-dialog.component.html
------------
Updates styling of close buttons to Bootstrap 5. The issue persists in the toasts, but this must be addressed on the side of @ng-bootstrap (see https://github.com/ng-bootstrap/ng-bootstrap/issues/3899).
#2424 
> Update close-button style to Bs5

- projects/hslayers/src/components/compositions/schema.json
Layers style attribute should support string. It already does that de-facto, but schema didn't reflect it
https://github.com/hslayers/hslayers-ng/pull/2422
> fix: Align layers style attribute to laymans schema

- projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
- projects/hslayers/src/components/compositions/compositions.spec.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/test/data/composition.ts
Parse style from composition when loading WFS layers
#2420 
> fix: Parse style when loading WFS from compositions

- projects/hslayers/src/components/draw/partials/draw.html
- projects/hslayers/src/components/query/default-info-panel-body/default-info-panel-body.component.html
- projects/hslayers/src/components/query/feature-list/feature-list.component.html
- projects/hslayers/src/components/query/feature-list/feature-list.component.ts
- projects/hslayers/src/components/query/feature/feature.component.html
- projects/hslayers/src/components/query/feature/feature.component.ts
- projects/hslayers/src/components/query/query-base.service.ts
- projects/hslayers/src/components/query/query-wms.service.ts
Can't use ChangeDetectionStrategy and must monitor
HsQueryBaseService.data.features  directly, otherwise changes
are not detected on WMS feature info requests.
fix #2454
> fix: Query window feature info change detection

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/map-swipe/map-swipe.component.html
- projects/hslayers/src/components/map-swipe/map-swipe.component.scss
- projects/hslayers/src/components/map-swipe/map-swipe.component.ts
- projects/hslayers/src/components/map-swipe/map-swipe.service.ts
- projects/hslayers/src/config.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Set map swipe disabled by default and added mapSwipe to componentsEnabled, to enable it.
Created mapSwipeOptions object for setting swipe control orientation and potential place for future config addons.
Removed initialSwipeRight in favour of layer properties swipeSide property.
closes #2476 
> fix: Map swipe disabled by default (Issue-2476)

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/add-data/common/common.service.ts
- projects/hslayers/src/components/add-data/url/add-data-url-base.component.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/types/layer-options.type.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
Made small changes fixing getSubLayers by getting subLayers property instead of sublayers. When adding WMS services subLayers will store sublayer names only.
closes #2496 
> WMS layers sublayers should store array with layer names (Issue-2496)

- projects/hslayers/src/common/dom-feature-link.type.ts
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/external/external.service.ts
- projects/hslayers/src/components/external/public-api.ts
- projects/hslayers/src/components/query/feature/feature.component.ts
- projects/hslayers/src/hslayers.component.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.html
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Create a layer config property which defines what should happen to
a feature when user moves mouse over or clicks on a element outside hslayers.
The elements can be found for each feature by CSS selectors. Full config:
```
domFeatureLinks: [
{
domSelector: '#poly1',
feature: 'poly1',
event: 'mouseover',
actions: ['zoomToExtent'],
},
]
```
fixes #2428
> feat: Link feature actions to external element events

- projects/hslayers/src/components/add-data/vector/vector.service.ts
Layers  with url (those that are supposed to be synced with layman) were falling into else block thus not working properly
> fix: Setting of vector layer definition

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/add-data/common/common.service.ts
- projects/hslayers/src/components/add-data/common/url/add/add.component.html
- projects/hslayers/src/components/add-data/common/url/details/details.component.html
- projects/hslayers/src/components/add-data/common/url/details/details.component.ts
- projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
- projects/hslayers/src/components/add-data/url/add-data-url.service.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/types/layer-options.type.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.component.html
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts-service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts.component.html
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.spec.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.sub-layer-checkboxes.component.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.sub-layer.service.ts
- projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
- projects/hslayers/src/components/layermanager/logical-list/layer-list.spec.ts
- projects/hslayers/src/components/utils/layer-utils.service.ts
This allows adding arcgis service as a whole with all sub-layers queried by a single request.
#2459 
> Issue 2459/arcgis

- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/common/pager/pager.component.html
- projects/hslayers/src/common/pager/pager.component.ts
- projects/hslayers/src/common/pager/pager.module.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/compositions/compositions-catalogue.service.ts
- projects/hslayers/src/components/compositions/compositions.html
Added toggleable dropdown menu inside paging footer, for changing the count of records per page.
closes #2513 
> Ability to change records per page count using dropdown menu (Issue-2513)

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/common/common.service.ts
- projects/hslayers/src/components/add-data/common/url/add/add.component.html
- projects/hslayers/src/components/add-data/common/url/add/add.component.ts
- projects/hslayers/src/components/add-data/common/url/details/details.component.html
- projects/hslayers/src/components/add-data/common/url/details/details.component.ts
- projects/hslayers/src/components/add-data/common/url/nested-layers-table/nested-layers-table.component.html
- projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
- projects/hslayers/src/components/add-data/url/add-data-url.component.ts
- projects/hslayers/src/components/add-data/url/add-data-url.service.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
This PR allows the user to load a list of external services from which you can choose to load multiple services at once, or expand each of the services to select specific layers to add to the map. Currenly supported for Arcgis only.
None
> Ability to load external server list of services and add them to the map

- projects/hslayers-server/README.md
- projects/hslayers-server/package-lock.json
- projects/hslayers-server/package.json
- projects/hslayers-server/server.js
Users don't have to always want to run all the three services. Command line options are added to turn on/off single services. Readme is modified to describe those options and run script changed to use npx.
Closes #2337 
It is actually perfectly possible to run it with npx even now. The problem is missing .env which is now reported via console error.
> Add options to run only specified components of server

- projects/hslayers/src/components/utils/layer-utils.service.ts
- projects/hslayers/src/components/utils/utils.service.ts
When module federation is used modules sometimes are loaded in a wrapper which makes class checking fail
> fix: Make instance checking more robust when mod-fed is used

- projects/hslayers/src/components/layout/layout.service.ts
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/layout/partials/layout.component.scss
- projects/hslayers/src/components/layout/partials/layout.html
- projects/hslayers/src/components/sidebar/sidebar.service.ts
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
- projects/hslayers/src/css/hslayers-wo-bootstrap.scss
- projects/hslayers/src/hslayers.component.ts
Because panelSpaceWidth function is called on every digest cycle twice so I tought it might be quite beneficial for us to replace it with something more efficient which would be css. The problematic part is that the new approach must be able to handle dynamicaly created panel that are not part of the library which makes panel specific css classes unusable .
So I tought we might make a little trade off of absolute freedom of width declaration using for example 14 predefined 'size classes' generated like so:
```
@for $i from 0 through 14{
.hs-panelspace hs-panel-container .hs-panelWidth-#{400 + ($i * 25) } {
width: 400 + ($i * 25)+px;
}
//Output:
.hsl .hs-panelspace hs-panel-container .hs-panelWidth-400 {
width: 400px;
}
.hsl .hs-panelspace hs-panel-container .hs-panelWidth-425 {
width: …
```
> perf: Remove usage of panelSpaceWidth function

- projects/hslayers/src/components/add-data/url/wms/wms.spec.ts
- projects/hslayers/src/components/layout/layout.service.mock.ts
- projects/hslayers/src/components/layout/layout.service.ts
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/layout/panels/panel-container.service.interface.ts
- projects/hslayers/src/components/layout/panels/panel-container.service.ts
- projects/hslayers/src/components/measure/measure.component.ts
- projects/hslayers/src/components/measure/measure.spec.ts
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/hslayers.component.ts
Panel widths for external panels where not applied when switching back and forth between active panel.
This PR also rewrites the way how panels are enabled and disabled by default. Instead of having a separate object to manage default statuses, we set those on HsConfig.panelsEnabled instead. Otherwise wrong  panels are enabled incorrectly when HsConfig.update is called repeatedly, because HsConfig.panelsEnabled isn't undefined anymore.
https://github.com/hslayers/hslayers-ng/pull/2549
> Fix panel width resetting and refactor enabling panels

- projects/hslayers/src/components/layermanager/editor/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.html
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
Recreate layer editor widgets because widget container component is also recreated and distruction of it led to destruction of widget list
fixes #2602
> fix: Missing layer editor widgets after second toggle

- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/components/query/query-popup/query-popup.component.html
- projects/hslayers/src/components/query/query-vector.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Multiple layers can have features with the same id. In that case we need to loop through feature
collections and compare by feature instance instead.
fix #2617
> fix: Finding of correct layer when feature IDs overlap

- projects/hslayers/src/components/layermanager/widgets/scale-widget.component.ts
changeDetection: ChangeDetectionStrategy.OnPush was causing the scale value to stay the same even when layers where changed without closing the scale widged
closes #2629 
> Layer scale settings changes in LayerManager when layers are switched

- projects/hslayers/src/components/external/external.service.ts
Correctly remove linked external actions for DOM elements, when layer is removed
fixes #2635
> fix: Correctly remove external actions on layer removal

- projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
Use infinite (but dont show in layer editor as Infinite) maxScaleDenominator for the container wms layer if its not set.
In case MaxScaleDenominator attribute does exist on the container layer in capabilities, recurse the sublayers to stretch resolution range, like it used to be before.
This PR also fixes the problem, that in case when both sublayers and LAYERS param as container layer name are specified on the OL layer LAYERS params is prioritised. It should be the other way - sublayers should be prioritized.
https://github.com/hslayers/hslayers-ng/issues/2639
> fix: Container layer not rendered when one of the sub-layers has resolution restriction

- projects/hslayers/src/components/styles/styler.service.ts
- projects/hslayers/src/components/styles/symbolizers/text-symbolizer/text-symbolizer.component.html
emitChange and rerender on selecting font in styler->text-symbolizer
fixes #2637
> fix: Render font in styler imediately after change

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/add-data/common/url/add/add.component.ts
- projects/hslayers/src/components/add-data/common/url/details/details.component.ts
- projects/hslayers/src/components/add-data/file/file-base.component.ts
- projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/public-api.ts
- projects/hslayers/src/components/add-data/url/types/ows-connection.type.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts.component.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts.service.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
- projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
- projects/hslayers/src/components/layermanager/layermanager-metadata.service.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
By setting loadProgress.error = false; on imageloadstart and tileloadstart, the 'Layer not available' will be removed until all tiles fail to load, then it will be visible. When to connection returns, the message will be removed once again
closes #2632
> Clear 'Layer not available' on each tile load start (Issue-2632)

- projects/hslayers/src/components/add-data/vector/vector-layer-options.type.ts
- projects/hslayers/src/components/add-data/vector/vector.service.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/map-swipe/map-swipe.service.mock.ts
- projects/hslayers/src/components/map-swipe/map-swipe.service.spec.ts
- projects/hslayers/src/components/map-swipe/map-swipe.service.ts
- projects/hslayers/src/components/map-swipe/swipe-control/swipe.control.class.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
This PR provides requested features from the feature issue, such as, map-swipe custom URL parameter, that is used to check the state of the swipe control state.
Map swipe control position and orientation is now stored to local storage.
When the map composition is being shared or stored to local storage, swipeSide property is set for each layer, so it can be obtained.
closes #2633 
closes #2655 
> Map swipe state in url, swipe control properties stored to local storage (Issue 2633)

- projects/hslayers/src/components/query/query-popup-base.service.ts
Hide popup for layers where it's not configured
fixes #2672
> fix: Hide popup for layers where it's not configured

- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
Look for wms layers with 'Name' parameter without the 'depth' limit . 
Example service which we were not able to correctly parse layer from :
https://geoportal.gov.cz/arcgis/services/CENIA/cenia_copernicus_land/MapServer/WmsServer?request=GetCapabilities&service=WMS&version=1.3.0
**Structure:** 
Capabilities -> Layer -> Layer (title: Lokalni kompnenta) -> Layer (title: Natura 2000) ->  Layer (name:0)
> fix: Look for wms layers with name recursively

- projects/hslayers/src/components/external/external.service.ts
Checks layer visibility when handling feature actions
closes #2680 
> Check if layer is visible, when handling feature custom actions (Issue 2680)

- projects/hslayers/src/components/print/print-legend.service.ts
Quick fix for print wms layer legend height
None
> fix(print): Provide correct wms layer legend height

- projects/hslayers/src/components/add-data/add-data.component.ts
- projects/hslayers/src/components/add-data/url/add-data-url.component.ts
Fix [serviceType]_to_connect url param.  Tested with WMS on both multiapp and single app view eg. wms_to_connect=http://services.cuzk.cz/wms/wms.asp&wms_layers=KN_I
wms_to_connect=http://services.cuzk.cz/wms/wms.asp
> fix: connectServiceFromUrlParam

- projects/hslayers-server/package.json
- projects/hslayers-server/src/layman.js
Add missing username reservation in Layman when logging in from the map.
Closes #2923
> Ensure Layman username at first login

- projects/hslayers/src/components/add-data/url/wmts/wmts.component.html
Resolves WMTS checkbox issue
closes #2928  
> Provide correct attr bound id for checkbox and label (Issue-2928)

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/map-swipe/map-swipe.service.ts
- projects/hslayers/src/components/map-swipe/swipe-control/swipe.control.class.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
This PR resolves issue, when map swipe is active, the info tool is querying layers no matter in which panel they are.
closes #2902 
> Create queryFilter for layer when mapSwipe is enabled (Issue-2902)

- projects/hslayers/src/common/get-capabilities/dimension.service.ts
- projects/hslayers/src/components/layermanager/dimensions/layer-editor-dimensions.component.ts
- projects/hslayers/src/components/layermanager/dimensions/layer-editor-dimensions.html
- projects/hslayers/src/components/layermanager/editor/layer-editor.spec.ts
- projects/hslayers/src/components/layermanager/widgets/cluster-widget.component.ts
- projects/hslayers/src/components/layermanager/widgets/layer-editor-widget-base.component.ts
- projects/hslayers/src/components/layermanager/widgets/legend-widget.component.html
- projects/hslayers/src/components/layermanager/widgets/metadata-widget.component.html
- projects/hslayers/src/components/layermanager/widgets/metadata-widget.component.ts
- projects/hslayers/src/components/layermanager/widgets/opacity-widget.component.ts
- projects/hslayers/src/components/layermanager/widgets/scale-widget.component.ts
- projects/hslayers/src/components/layermanager/widgets/type-widget.component.html
- projects/hslayers/src/components/utils/layer-utils.service.ts
This solves error when dimensions are not displayed in editor.
Using observable to to monitor if current edited layer changes is more error prone and performs better.
> refactor: Monitor currentLayer in widgets by observable

- projects/hslayers/src/components/compositions/compositions.component.html
- projects/hslayers/src/components/compositions/compositions.component.ts
Hide save map button, if saveMap panel is disabled
closes #2946 
> Hide save map button, if saveMap panel is disabled (Issue-2946)

- projects/hslayers/src/components/layout/layout.service.ts
When creating panel or overlay using Layout service, app property should be optional as it is for the container service
None
> CreatePanel and createOverlay app should be optional

- projects/hslayers/src/components/compositions/compositions-parser.service.ts
If the user requests to overwrite map content, any layer that is not base layer or does not specify 'removable' layer propery will get removed.
closes #2875 
> Remove map content when loading composition (Issue 2875)

- projects/hslayers-sensors/src/components/sensors/partials/unit-list-item.component.html
- projects/hslayers-sensors/src/components/sensors/sensors.service.ts
This tries to solve very bad performance, when having around 100 sensor units on the field with ~8 sensors each.
> Rostenice fixes

- projects/hslayers/src/components/sidebar/mini-sidebar.component.ts
- projects/hslayers/src/components/sidebar/sidebar.component.ts
- projects/hslayers/src/components/sidebar/sidebar.service.ts
Small fix fix for broken button order after window is resized
Important part is
```
this.HsEventBusService.layoutResizes
.pipe(takeUntil(this.end))
.subscribe(() => {
this.HsSidebarService.setButtonVisibility(this.buttons, this.app);
});
```
where visibility is set on the already subscribed, sorted, and title-function handled buttons not the ones which reside in the buttonSubject which is later not even propagated from service to components. The rest is just styling.
https://github.com/hslayers/hslayers-ng/issues/2971
> fix: Sidebar button order after layout resize

- projects/hslayers/src/common/layers/hs.source.interpolated.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Use getter and setter to allow dynamic weight values
> refactor: Use getter and setter to allow dynamic weight values

- projects/test-app/src/hslayers-app/hslayers-app.component.ts
- projects/test-app/src/hslayers-app/hslayers-app.module.ts
- projects/test-app/src/hslayers-app/some-panel/some-panel.component.html
- projects/test-app/src/hslayers-app/some-panel/some-panel.component.ts
- projects/test-app/src/hslayers-app/some-panel/some-panel.module.ts
Creating a custom panel is not covered by our test cases so far. For testing the PR #2988 I have aligned the test-app accordingly. I am publishing the changes here in this branch and opening a discussion whether we want to include this use-case in the test-app as default (i.e. merging this PR) or rather keep the test-app as simple as possible (i.e. closing it without merging).
#2988
> Add custom panel to the test-app

- projects/hslayers/src/common/layman/types/delete-layer-response.type.ts
- projects/hslayers/src/components/draw/draw.service.ts
- projects/hslayers/src/components/save-map/layman.service.ts
When trying to delete multiple layers using the multiple layer removal dialog, we were passing function params incorrecly, which led to all layers being deleted from Layman and HSLayers.
Also fixed toast messeges when deleting
None
> Fixed multiple layer removal

- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/common/layers/hs.source.interpolated.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/layermanager.module.ts
- projects/hslayers/src/components/layermanager/public-api.ts
- projects/hslayers/src/components/layermanager/widgets/idw-widget.component.html
- projects/hslayers/src/components/layermanager/widgets/idw-widget.component.ts
- projects/hslayers/src/components/layout/layout.component.ts
- projects/hslayers/src/components/layout/layout.service.ts
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/sidebar/mini-sidebar.component.ts
- projects/hslayers/src/components/sidebar/partials/sidebar.html
- projects/hslayers/src/components/sidebar/sidebar.component.ts
- projects/hslayers/src/components/styles/add-colormap.component.ts
- projects/hslayers/src/components/styles/add-colormap.html
- projects/hslayers/src/components/styles/public-api.ts
- projects/hslayers/src/components/styles/styler.component.html
- projects/hslayers/src/components/styles/styler.service.ts
- projects/hslayers/src/components/styles/styles.module.ts
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/hslayers.component.ts
A widget in layer editor which allows setting attribute which to visualize, color map and value interval in which to visualize
Min, max options now can be added to InterpolatedSource constructor
> feat: Widget for setting bounds and colormap for IDW layer

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/fr.json
- projects/hslayers/src/assets/locales/nl.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/layermanager/layermanager.html
- projects/hslayers/src/css/hslayers-bootstrap.scss
Move the toggle button of physical layer list from the dropdown menu to the panel to make it more visible. Rename it to "Layer reordering" to make its purpose more clear.
> Make physical list of layers more visible and rename it

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
- projects/hslayers/src/components/add-data/file/shp/shp.component.html
- projects/hslayers/src/components/add-data/vector/vector.service.ts
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/components/save-map/dialog-save/dialog-save.component.html
- projects/hslayers/src/components/save-map/dialog-save/dialog-save.component.ts
- projects/hslayers/src/components/save-map/form/form.component.html
- projects/hslayers/src/components/save-map/form/form.component.ts
- projects/hslayers/src/components/save-map/layman.service.ts
- projects/hslayers/src/components/save-map/save-map-manager.service.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/hslayers/src/components/save-map/types/compo-data.type.ts
For better user experience changed layer upload input form and map compostion saving form, going from title to name property instead. Layer title gets updated to the same name in case of any change.
Check if default_view is defined, when trying to get center and zoom.
Find 4326 proj. from aliases when uploading geojson file and check for supported SRS.
Don't wait for prev. uploaded vector layer to finish, if User tries to overwrite it instantly.
None
> Use name property in UI for layer upload and composition saving, + other fixes

- projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.html
- projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Don't use hardcoded 'cs' locale which isn't even a valid value for timeFormat. Use HsConfig.timeDisplayFormat instead
#3126 
> fix: Formatt time by config instead of hardcoded cs

- projects/hslayers/src/components/query/attribute-row/attribute-row.component.ts
Attribute value gets not set on feature when we change it. Got broken after supporting json objects as attribute values.
> Setting of attr value

- projects/hslayers/src/common/get-capabilities/dimension-time.service.ts
- projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.ts
- projects/hslayers/src/components/query/attribute-row/attribute-row.component.ts
This PR introduces monitoring of TIME parameter in TileWMS and ImageWMS source objects accessed through getParams(). This is needed for map-whiteboard to synchronize time layers between users and we don't want to use Hslayers classes to do that - just map whiteboard library.
TIME request parameter in layer definition takes precedence over dimension definitions when calculating default initial time.
> feat: Update dimension from TIME param im WMS sources

- projects/hslayers/src/components/layout/dialogs/dialog-container.service.ts
- projects/test-statistics-app/src/app/app.component.ts
- projects/test-statistics-app/src/app/app.module.ts
- projects/test-statistics-app/src/app/info-dialog.component.html
- projects/test-statistics-app/src/app/info.component.ts
Replay the values stored in dialogObserver object when subscribing
fix #3190
> fix: Show dialogs also when they are created on startup

- projects/hslayers/src/components/core/core.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Resolves issue 3258
closes #3258 
> Fix sidebar language panel abbreviation, if language is set in hsConfig (Issue-3258)

- projects/hslayers/src/components/layout/layout.component.ts
- projects/hslayers/src/components/layout/layout.service.ts
- projects/hslayers/src/components/permalink/partials/share.component.html
- projects/hslayers/src/components/permalink/share-thumbnail.service.ts
- projects/hslayers/src/components/permalink/share-url.service.ts
- projects/hslayers/src/components/permalink/share.component.ts
- projects/hslayers/src/components/permalink/share.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.html
Permalink generation gets reenabled in multi-app mode now. It adds a new GET param 'app' depending from which apps 'share' panel it was was called / displayed in. When hslayers is loaded the the page scrolls to the app specified in aforementioned GET param.
#2821 
> feat: Scroll to app if it's present in the URL

- projects/hslayers/src/components/add-data/url/geosparql/geosparql.service.ts
- projects/hslayers/src/components/layout/panels/panel-container.component.ts
- projects/hslayers/src/components/layout/panels/panel-container.service.ts
- projects/hslayers/src/config.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Correctly sets panelWiths Hsconfig property.
Removed deprecated function signature (code simplification).
Runtime safety.
Stylistics.
#3309 
> Set panel widths correctly + refactoring

- projects/hslayers-cesium/src/hscesium-layers.service.ts
- projects/hslayers/src/components/compositions/compositions.service.ts
- projects/hslayers/src/components/map/map.component.ts
- projects/hslayers/src/components/map/map.service.ts
Filter default_layers and box_layers by removable property if default composition or hs-composition in URL is set.
Do not add any hsConfig's layers, if hs-permalink in URL is set.
Set visibleLayersInUrl for each app's map service.
closes #3335 
> Initial layer loading refactoring

- projects/hslayers/src/common/layers/hs.source.interpolated.ts
This fixes custom color maps in ol-ext 4 version for IDW layers. getColor function is encapsulated there and not exposed in IDwSource prototype which broke the custom color map functionality.
> fix: Custom color maps on ol-ext 4 IDW layers

- projects/hslayers/src/components/draw/draw-panel/draw-panel.component.ts
- projects/hslayers/src/components/draw/draw.component.ts
- projects/hslayers/src/components/layout/dialogs/dialog-container.component.ts
- projects/hslayers/src/components/layout/dialogs/dialog-container.service.ts
- projects/hslayers/src/components/layout/layout.component.ts
- projects/hslayers/src/components/query/query-popup-widget-container.service.ts
- projects/hslayers/src/components/query/query-popup/query-popup.component.ts
- projects/hslayers/src/components/sidebar/sidebar.component.ts
Clean up dialog/widget replaySubjects when container components get destroyed.
#3445 3445
> fix: Clean up replay subjects when destroying containers

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.ts
- projects/hslayers/src/components/add-data/file/file-base.component.ts
- projects/hslayers/src/components/add-data/file/file.service.ts
- projects/hslayers/src/components/add-data/file/types/file-data-object.type.ts
- projects/hslayers/src/components/add-data/vector/vector-data.type.ts
- projects/hslayers/src/components/add-data/vector/vector-descriptors/vector-layer-descriptor.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
- projects/hslayers/src/components/add-data/vector/vector-layer-options.type.ts
- projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
- projects/hslayers/src/components/add-data/vector/vector.service.ts
- projects/hslayers/src/components/save-map/layman.service.ts
- projects/hslayers/src/components/save-map/types/upsert-layer-object.type.ts
- projects/hslayers/src/components/styles/styler.component.html
- projects/hslayers/src/components/styles/styler.component.ts
- projects/hslayers/src/components/styles/styler.service.ts
Support upload of QML in style panel and create a walkaround for invalid WellKnownName problem when parsing qml with geostyler-qml-parser.
https://github.com/hslayers/hslayers-ng/issues/3433
https://github.com/hslayers/hslayers-ng/issues/3431
> Upload QML (Issue 3433)

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/fr.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/nl.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.html
- projects/hslayers/src/components/layermanager/gallery/basemap-gallery.html
- projects/hslayers/src/components/layermanager/gallery/layermanager-gallery.component.ts
- projects/hslayers/src/components/layermanager/layer-descriptor.interface.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/hslayers/src/components/save-map/types/layer-json.type.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
- projects/hslayers/src/css/hslayers-wo-bootstrap.scss
Make use of 'greyscale' attribute of map composition schema.
Aligned usage of gray vs grey to match composition schema.  Apparently gray is more American (https://www.grammarly.com/blog/gray-grey/).  
Thinking about it now Id probably prefer gray as CSS filter rule is named 'grayscale' with a.  But nvm
fixes #3346 
> feat: Use grayscale map composition param

- .gitignore
- projects/hslayers-server/.env.example
- projects/hslayers-server/src/layman.js
Since [passport@0.6.0](https://github.com/jaredhanson/passport/blob/v0.6.0/CHANGELOG.md), req.logout() has a mandatory callback function param. Not providing it was throwing an error, effectively blocking the actual log-out action.
resolves #3605 
> hslayers-server: Provide callback for logout()

- projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue.component.html
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.html
- projects/hslayers/src/components/add-data/common/url/progress/progress.component.html
- projects/hslayers/src/components/add-data/url/wfs/wfs.component.html
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.html
- projects/hslayers/src/components/compositions/compositions.component.html
- projects/hslayers/src/components/compositions/dialogs/csw-layers-dialog/csw-layers-dialog.component.html
- projects/hslayers/src/components/draw/partials/draw.html
- projects/hslayers/src/components/print/print.component.html
- projects/hslayers/src/components/trip-planner/trip-planner.component.ts
- projects/hslayers/src/components/trip-planner/trip_planner.html
- projects/hslayers/src/config.service.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
The old "ajaxLoaderIcon" is so last year. Even thought the image itself is tiny, so it is not an issue with bundle size, its appearance on the site relies on properly set assetsPath. That can cause troubles and represents a bottle-neck. Additionally, the old loader in gray colours creates a bad visual readability on a blue background (used on buttons). The new loader icon is composed by SCSS transitions and animations. It also creates a unique UI, instead of an echo of late 2000s design. Most of the code was borrowed from https://cssloaders.github.io/
Removing the old icon from the repo can be considered a breaking change, thus for now I have only marked it as deprecated.
none
> Replace loader icon with a CSS loader

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.ts
- projects/hslayers/src/components/add-data/catalogue/layman/layman.service.ts
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.html
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.ts
- projects/hslayers/src/components/add-data/common/advanced-options/advanced-options.component.html
- projects/hslayers/src/components/add-data/common/advanced-options/advanced-options.component.ts
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/common/common.service.ts
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
- projects/hslayers/src/components/add-data/common/save-to-layman/save-to-layman.component.html
- projects/hslayers/src/components/add-data/common/save-to-layman/save-to-layman.component.ts
- projects/hslayers/src/components/add-data/enums/load-types.const.ts
- projects/hslayers/src/components/add-data/file/file-base.component.ts
- projects/hslayers/src/components/add-data/file/shp/shp.component.ts
- projects/hslayers/src/components/add-data/file/types/file-data-object.type.ts
- projects/hslayers/src/components/add-data/public-api.ts
- projects/hslayers/src/components/add-data/url/add-data-url.component.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
- projects/hslayers/src/components/add-data/vector/vector.service.ts
- projects/hslayers/src/components/compositions/compositions.spec.ts
- projects/hslayers/src/components/draw/draw.service.ts
- projects/hslayers/src/components/layermanager/gallery/basemap-gallery.html
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/save-map/interfaces/layman-layer-descriptor.interface.ts
- projects/hslayers/src/components/save-map/layer-synchronizer.service.ts
- projects/hslayers/src/components/save-map/layman.service.ts
New switcher in Advanced Options which adds possibility to:
* load Shapefile as a WFS service (previously only WMS was possible) and
* load KML/GeoJSON as a WMS service (previously only WFS was possible)
Also adding a brief description about what the "save to database" actually means and how it behaves (hidden by default).
resolves #3440 
> Add load as WMS/WFS switcher to add-data

- projects/hslayers/src/components/layermanager/dimensions/layermanager-time-editor.component.html
- projects/hslayers/src/components/layermanager/layermanager.html
- projects/hslayers/src/components/layermanager/logical-list/layerlist.html
- projects/hslayers/src/components/layermanager/physical-list/physical-layerlist.component.html
- projects/hslayers/src/components/styles/styler.component.html
- projects/hslayers/src/components/styles/symbolizers/fill-symbolizer/fill-symbolizer.component.html
- projects/hslayers/src/components/styles/symbolizers/line-symbolizer/line-symbolizer.component.html
Add margin to controlls which are displayed under scrollbar in styler and layermanager
#3648 
> style: Fix overlaying scrollbars in layers, styler

- package-lock.json
- projects/hslayers/src/components/add-data/add-data.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue.component.html
- projects/hslayers/src/components/compositions/compositions.component.html
Excess height of add-data and composition lists were triggering `extentChange` event (by changing map width when the scrollbar appeared)
Fixed by moving scroll deeper into DOM - now only panel content shrinks.
Compositions panel:
For add-data panel it was a bit different because of different DOM structure.  The issue is fixed, but scrolling behaviour of some of the elements is a bit different than expected I'd say (different from the composition panel at very least). 
I was not able to keep both add-data tabs (catalogue,URL,file) and catalogue header visible.. Its one or the other.
I chose the header because the other option affects not only catalogue but other tabs (for example when adding WMS layer, tabs would be visible when scrolling). Not that it would look bad its just change from …
> Fix composition/add-data item list overflow triggering map extent change

- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
> fix: Wrong usage of nullish coalescing operator when trasforming WMS bbox

- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/map/map.service.ts
When adding new layer, check wether it already it exists or not. If so, remove duplicate
fixes #3756
> Remove already existing layer

- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/compositions/schema.json
------------
Created WFS layer was not passed on to the rest of the code (missing variable assignment).
Additionally, the createWFSLayer() method was returning an array (de facto always 1-length), instead of a single item, as expected.
resolves #3817
> Pass on created WFS layer

- projects/hslayers-server/src/proxy.js
Some other clients using our proxy can send encoded URI (old HSLayers). Decode the URI in that case.
> fix: Decode proxyfied url in case client send it that way

- cypress/tests/add-data.cy.ts
- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.html
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.ts
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.html
- projects/hslayers/src/components/add-data/common/new-layer-form/new-layer-form.component.ts
- projects/hslayers/src/components/add-data/file/file-base.component.ts
- projects/hslayers/src/components/add-data/file/file-type-values.ts
- projects/hslayers/src/components/add-data/file/file.component.html
- projects/hslayers/src/components/add-data/file/raster/raster-timeseries/raster-timeseries.component.html
- projects/hslayers/src/components/add-data/file/raster/raster-timeseries/raster-timeseries.component.scss
- projects/hslayers/src/components/add-data/file/raster/raster-timeseries/raster-timeseries.component.ts
- projects/hslayers/src/components/add-data/file/raster/raster.component.html
- projects/hslayers/src/components/add-data/file/raster/raster.component.ts
- projects/hslayers/src/components/add-data/file/raster/raster.module.ts
- projects/hslayers/src/components/add-data/file/types/file-data-object.type.ts
- projects/hslayers/src/components/add-data/file/types/file-form-data.type.ts
- projects/hslayers/src/components/add-data/file/types/file.type.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/compositions/schema.json
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/components/save-map/interfaces/layman-layer-descriptor.interface.ts
- projects/hslayers/src/components/save-map/layman.service.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
- Implement raster series upload to Layman
Currently works with raster series files that:
- matche one of the following regex datetime formats 
-[0-9]{8}T[0-9]{9}Z eg 20220510T050948Z
-[0-9]{8}T[0-9]{9} eg. 20220510T050948
- consist of digits only or digits and separators  ., _, /, or -
For the regex patterns listed  I dont really know wether these are the most used . I took those from [layman docs](https://github.com/LayerManager/layman/blob/v1.18.0/doc/rest.md#post-workspace-layers). 
We can always add/edit this.
- Allow all CRS from supported CRS list to be used with rasters.
closes #3755 
> Raster timeseries

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/common/get-capabilities/arcgis-get-capabilities.service.ts
- projects/hslayers/src/common/get-capabilities/wfs-get-capabilities.service.ts
- projects/hslayers/src/common/get-capabilities/wms-get-capabilities.service.ts
- projects/hslayers/src/common/get-capabilities/wmts-get-capabilities.service.ts
- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/file/types/file-form-data.type.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/vector/vector-data.type.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.ts
- projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.ts
- When trying to add data from url that returns HTML document its not expected to include any valid data thus it shold be treated as an error
"+"
- fix: Add allowedStyles adddata param to missing data types introduced in 83d4cdd
- Cancel remaining feature count reqeusts if current fails
#3899 
> 3899 - Don't add layer which cannot be added

- package-lock.json
- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/common/url/add/add.component.ts
- projects/hslayers/src/components/add-data/common/url/layer-table/layer-table.component.html
- projects/hslayers/src/components/add-data/common/url/layer-table/layer-table.component.ts
- projects/hslayers/src/components/add-data/url/add-data-ows.service.ts
- projects/hslayers/src/components/add-data/url/add-data-url.service.ts
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/models/url-type-service.model.ts
- projects/hslayers/src/components/add-data/url/types/argis-response-type.ts
- projects/hslayers/src/components/add-data/url/types/data-object.type.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts.service.ts
- added zoomToLayers functionality for WMTS and ArcGIS services.  Initial zoom is calculated as combination of extents of each selected layer
fixes #3819
> ZoomToLayers method for WMTS and ArcGIS services

- projects/hslayers/src/common/layers/hs.source.WfsSource.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
HsCompositionsParserService.jsonToLayer doesnt return a layer when lyr_def.protocol?.format == 'hs.format.externalWFS' is used. This prevents external WFS layers in whiteboard (they are handled like oridinary vector layers by mw library, not haslayers instead)
This is fixed in this PR by utilizing common/layers/hs.source.WfsSource
Had problems with SRS because corrdinate pairs where switched in BBOX and in GML response. Tried to fix it for EPSG:4326, but special case for 4258 still remains 
```
if (/*srs.includes('4326') || */ srs.includes('4258')) {
```
Need to check that
This also supports a new `version` attribute in the composition schema which specifies VERSION param used in WFS requests:
```
"protocol":{
"url":"https://hub4everybody.com/geoserver/jan_vrobel/wfs", …
```
> fix: Load external wfs layers without add layers panel

- projects/hslayers/src/components/add-data/vector/vector.service.ts
- projects/hslayers/src/components/save-map/save-map.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
Prefer QML and SLD styles over custom format when loading layer from composition
backported from #3945 by @FilipLeitner
resolves #3943
> Prefer QML and SLD styles over custom format when loading layer from composition

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
- projects/hslayers/src/components/core/event-bus.service.ts
- projects/hslayers/src/components/draw/draw.service.ts
- projects/hslayers/src/components/feature-table/feature-table.service.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor-vector-layer.service.ts
- projects/hslayers/src/components/legend/legend.service.ts
- projects/hslayers/src/components/query/feature-common.service.ts
- projects/hslayers/src/components/query/query-base.service.ts
- projects/hslayers/src/components/styles/styler.service.ts
This PR addresses issue #4042 , namely the situation when multiple clustered layers are added to map. In that case, styling code is faster then the code responsible for changing the layer's source from `VectorLayer` to `Cluster`. That leads to improper style application (see #4042). I am addressing it by manually waiting for a `change:source` event if such situation occurs. On my machine, the issue was present when 6 or more clustered layers were in the map (from the beginning, via HsConfig). Now tested with 100 layers with no problem.
resolves #4042
> Fix cluster style with multiple clustered layers

- projects/hslayers/src/common/queues/queues.service.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/compositions/compositions-catalogue.service.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/components/map/map.spec.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Queue map content loading. Tried using same que for both tiled and non-tiled image layers but it seems like having two ques works better. Slow images can occupy 4 request 'slots' while tiles are still able to load alongside. In case of one queue image layers can block everything which doesn't feel great from the user perspective. 
So I decided for:
- tiled images: could request capped at 6 as these are normally pretty quick and frequent so  if any other requests are made its easy for them to sneak through. These would probably be ok even without a queue 
- image layers. 4 requests without timeout so it'll just wait until at least one finishes before creating new req.
- another small thing in here is change of default layer.dimenions value from empty object to undefined as empty object is …
> Issue 4058

- projects/hslayers/src/hslayers.layman.interceptor.ts
- projects/hslayers/src/hslayers.module.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
fix: Returned layman urls not pointing on layman-proxy if used
> URL replacement in Layman's publication descriptions

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/compositions/compositions.component.ts
- projects/hslayers/src/components/compositions/compositions.service.ts
- projects/hslayers/src/components/compositions/dialogs/dialog_overwriteconfirm.html
- projects/hslayers/src/components/compositions/dialogs/overwrite-dialog.component.ts
- projects/hslayers/src/components/layermanager/layermanager.component.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
Add possiblity to merge unedited compositions.
Fixed - Basemap composition is not 'composition' in the true sense but rather a specific way of defining initial map content and thus it should be handled specifically eg. not compositon_loaded should be assigned, added layers should not trigger composition layer events
Small adjustment of composition overwrite dialog UI/content
closes #4029
> Merge unedited compositions (Issue 4029)

- projects/hslayers/src/common/layman/layman-current-user.component.ts
- projects/hslayers/src/common/layman/layman.service.ts
Only request current-user for Layman endpoint, as it is not implemented for Micka.
~TODO: solve "Micka 200" toast message.~ Forked into #4215 
Port of #3957
Resolves #3915
> Request current-user only for Layman endpoint (12.x)

- projects/hslayers/src/common/layers/hs.source.WfsSource.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/core/event-bus.service.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
Custom loader in WfsSource never fired (dispatched, casted, ...) `'propertychange'`, `'featuresloadstart'`, `'featuresloadend'` or `'featuresloaderror'` events. Mitigated by dispatching them manually, so the code in [layermanager.service.ts](https://github.com/hslayers/hslayers-ng/blob/2af194b98df263bca70145fe128dafa222d4e3a4/projects/hslayers/src/components/layermanager/layermanager.service.ts#L853) can listen to them.
fixes #4041 
> Dispatch loading events for WfsSource

- projects/hslayers-sensors/src/components/sensors/sensors.service.ts
- projects/hslayers/src/.browserslistrc
- projects/hslayers/src/components/add-data/url/arcgis/arcgis.service.ts
- projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
- projects/hslayers/src/components/add-data/url/wmts/wmts.service.ts
- projects/hslayers/src/components/compositions/layer-parser/layer-parser.service.ts
Zooming onto layers loaded from composition via OWS connection is not desired as it cancel out composition initial view settings.
> fix: Dont zoom on OWS layers from compositions

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/common/save-to-layman/save-to-layman.component.html
- projects/hslayers/src/components/compositions/dialogs/overwrite-dialog.component.html
- projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
- projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts
- projects/hslayers/src/components/compositions/models/composition-descriptor.model.ts
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/components/query/feature/feature.component.html
- projects/hslayers/src/components/styles/filters/add-filter-button.component.ts
- projects/hslayers/src/components/styles/filters/comparison-filter.component.html
- projects/hslayers/src/components/styles/filters/comparison-filter.component.ts
- projects/hslayers/src/components/styles/filters/filters.component.ts
- projects/hslayers/src/components/styles/filters/filters.service.ts
- projects/hslayers/src/components/styles/styler.component.html
- projects/hslayers/src/components/styles/styler.component.ts
- projects/hslayers/src/components/styles/styler.service.ts
Styler related fixes.
-AND/OR filters were not preserved on panel change or in the resulting SLD because their interface was incorrectly implemented
- fix NOT filter by adding the specific case
-  #4447 seems to be fixed by  recretaing styles on reorder as well
-  make comarison operator dropdwon select. Took values from [here](https://geostyler.github.io/geostyler/#/Components/Filter/FilterTree)
closes #4447
> Styler filers and rules order

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/common/add-to-map/add-to-map.component.ts
- projects/hslayers/src/common/add-to-map/public-api.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.html
- projects/hslayers/src/components/add-data/common/add-layer-authorized/add-layer-authorized.component.html
- projects/hslayers/src/components/add-data/common/common.module.ts
- projects/hslayers/src/components/add-data/common/url/add/add.component.html
- projects/hslayers/src/components/add-data/common/url/details/details.component.html
- projects/hslayers/src/components/add-data/common/url/layer-table/layer-table.component.html
- projects/hslayers/src/components/add-data/common/url/url.module.ts
- projects/hslayers/src/components/add-data/url/geosparql/geosparql.component.html
- projects/hslayers/src/components/add-data/url/geosparql/geosparql.module.ts
- projects/hslayers/src/components/add-data/vector/vector-file/vector-file.component.html
- projects/hslayers/src/components/add-data/vector/vector-url/vector-url.component.html
- projects/hslayers/src/components/add-data/vector/vector.module.ts
- projects/hslayers/src/components/draw/draw-layer-metadata/draw-layer-metadata.html
- projects/hslayers/src/public-api.ts
Unify naming of the same action ("add to map") by reusing the same component
closes #4464 
> Reusable add-to-map button component

- projects/hslayers/src/components/add-data/common/common-file.service.ts
- projects/hslayers/src/components/add-data/vector/vector.service.ts
Make sure both service and style urls are ready when loading layer created by uploading file.
> fix: Make sure both style and service is ready after file upload

- projects/hslayers/src/assets/locales/cs.json
- projects/hslayers/src/assets/locales/en.json
- projects/hslayers/src/assets/locales/lv.json
- projects/hslayers/src/assets/locales/sk.json
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue-list-item/catalogue-list-item.component.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue-metadata/catalogue-metadata.component.html
- projects/hslayers/src/components/add-data/catalogue/catalogue-metadata/catalogue-metadata.component.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue-metadata/catalogue-metadata.module.ts
- projects/hslayers/src/components/add-data/catalogue/catalogue.service.ts
- projects/hslayers/src/components/add-data/catalogue/layer-descriptor.model.ts
- projects/hslayers/src/components/add-data/url/wms/wms.service.ts
- projects/hslayers/src/components/compositions/compositions.component.html
- projects/hslayers/src/components/compositions/layer-parser/composition-layer-options.type.ts
- projects/hslayers/src/components/layermanager/editor/layer-editor.component.ts
- projects/hslayers/src/components/layermanager/layermanager.module.ts
- projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.html
- projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.ts
- projects/hslayers/src/components/map/map.service.ts
- projects/hslayers/src/css/hslayers-bootstrap.scss
- projects/hslayers/src/css/hslayers-wo-bootstrap.scss
- fix layman image loading function - old que tasks not being cleaned as a result of no returned value
- ~add third add-data option WMTS - which is actually old WMS option (tiled WMS) while, new WMS option creates Image WMS layer~ see comments
- add layer-editor widget allowing switching between the types
https://github.com/hslayers/hslayers-ng/issues/4497
>  Layman image loading + WMS type widget + Micka metadata for datasets

- .github/workflows/build+test_libs_apps.yml
- .github/workflows/build+test_server.yml
- .github/workflows/nodejs.yml
- package.json
- projects/hslayers-server/.eslintrc.json
- projects/hslayers-server/.npmignore
- projects/hslayers-server/package-lock.json
- projects/hslayers-server/package.json
- projects/hslayers-server/server.js
- projects/hslayers-server/src/layman.js
- projects/hslayers-server/src/oauth2/session.js
- projects/hslayers-server/src/oauth2/util.js
- projects/hslayers-server/src/proxy.js
- projects/hslayers-server/src/share.js
- projects/hslayers-server/test/proxy.spec.js
Adding Mocha framework and Chai assertion library as new dependencies for the server. 
Rewritten all CommonJS modules to ES modules with updated imports/exports.
Bumps minimum Node version to 16 due to "got"
closes #3816
closes #4651
fixes #4635
fixes #4650 via a cherry-picked commit from #4678 
does not affect #3858 – albeit cors-anywhere last version was published 3 years ago, I haven't found any suitable alternative
Upgraded dependencies fix better-sqlite3 installation problems with node-gyp and glibc
> Create tests for hslayers-server and convert CommonJS files to ES syntax

- projects/hslayers/src/common/layer-extensions.ts
- projects/hslayers/src/components/compositions/compositions-parser.service.ts
- projects/hslayers/src/components/compositions/compositions.service.ts
- projects/hslayers/src/components/layermanager/layermanager.component.ts
- projects/hslayers/src/components/layermanager/layermanager.service.ts
fix issue #4650 for version 13.x
- fix zindex assignment of composition layers -> should  match the composition layer order and not be influenced by path's max zindex
- sort layers in folder based on hsConfig.reverseLayerList
#4650
> Permalink malformed & z-index of composition layer

- projects/hslayers/components/compositions/compositions.component.html
- projects/hslayers/components/compositions/compositions.component.ts
Disable "Save current map" button when Save map panel is not enabled
closes #4633
> Disable "Save current map" button when Save map panel is not enabled

- projects/hslayers/common/extensions/layer-extensions.ts
- projects/hslayers/components/compositions/compositions.service.ts
- projects/hslayers/shared/compositions/compositions-parser.service.ts
- projects/hslayers/shared/layer-manager/layer-manager.service.ts
- fix zindex assignment of composition layers -> should match the composition layer order and not be influenced by path's max zindex
- sort layers in folder based on hsConfig.reverseLayerList
fixes #4679
> Composition layer order (issue 4679)

- projects/hslayers/common/layers/hs.source.SparqlJson.ts
- projects/hslayers/components/info/info.component.html
- projects/hslayers/components/info/info.component.ts
- projects/hslayers/components/layer-manager/editor/layer-editor-sub-layer.service.ts
- projects/hslayers/components/layer-manager/editor/layer-editor.service.ts
- projects/hslayers/components/layer-manager/layer-manager.component.html
- projects/hslayers/components/layer-manager/layer-manager.component.scss
- projects/hslayers/components/layer-manager/layer-manager.module.ts
- projects/hslayers/components/layer-manager/logical-list/layer-manager-layerlist.component.html
- projects/hslayers/components/layer-manager/logical-list/layer-manager-layerlist.component.ts
- projects/hslayers/components/layer-manager/logical-list/layerlist.component.scss
- projects/hslayers/components/layer-manager/widgets/layer-editor-widget-base.component.ts
- projects/hslayers/components/legend/legend.service.ts
- projects/hslayers/shared/add-data/url/hs.source.WfsSource.ts
- projects/hslayers/shared/add-data/url/wfs.service.ts
- projects/hslayers/shared/event-bus/event-bus.service.ts
- projects/hslayers/shared/layer-manager/layer-manager-loading-progress.service.ts
- projects/hslayers/shared/layer-manager/layer-manager.service.ts
- projects/hslayers/types/layer-manager/layer-descriptor.interface.ts
- port of https://github.com/hslayers/hslayers-ng/commit/15008cdb09144dde4a0435e5682178a09672d33a
-  refactor existing layer loading counter and use it for map layers
closes #4705 
closes #4275 
> Loading progress and  WFS loading strategy,

- projects/hslayers-app/custom-webpack.config.js
- projects/hslayers-app/src/index.html
- projects/hslayers-cesium-app/custom-webpack.config.js
- projects/hslayers-cesium-app/src/index.html
Fix loading of lazy chunks by setting `publicPath: 'auto'` in the webpack's config.
release 14.0
> Fix script's publicPath

- projects/hslayers/config/config.service.ts
- projects/hslayers/services/query/query-vector.service.ts
- update config parma `query` with new attribute style allowing setting custom style for selected features without having to reassign selector
- fix adding a new selector
fixes #4888 
> Query selector

- angular.json
- projects/cesium-test-app/src/app/app.component.ts
- projects/hslayers-cesium/css/hslayers-cesium.scss
- projects/hslayers-cesium/src/hscesium.component.scss
- projects/hslayers-cesium/src/hscesium.component.ts
- projects/hslayers/components/layer-manager/gallery/layer-manager-gallery.component.scss
Prevent clash of basemapGallery and Cesium buttons. Unify styling of Cesium buttons and HSL/OL buttons.
Solution is not perfect, yet better than now.
none
> Align style of HSLayers/OpenLayers/Cesium buttons

- projects/hslayers-sensors/src/components/sensors/partials/sensors.component.html
- projects/hslayers-sensors/src/components/sensors/partials/unit-dialog.component.html
- projects/hslayers-sensors/src/components/sensors/partials/unit-list-item.component.html
- projects/hslayers-sensors/src/components/sensors/sensor-unit.class.ts
- projects/hslayers-sensors/src/components/sensors/sensors-unit-dialog.component.ts
- projects/hslayers-sensors/src/components/sensors/sensors-unit-list-item.component.ts
- projects/hslayers-sensors/src/components/sensors/sensors.component.ts
- projects/hslayers-sensors/src/components/sensors/sensors.service.ts
- projects/hslayers-sensors/src/components/sensors/types/senslog-response.type.ts
- projects/hslayers-sensors/src/components/sensors/types/senslog-sensor.type.ts
- projects/hslayers-sensors/src/components/sensors/unit-dialog.service.ts
- projects/hslayers-sensors/src/public-api.ts
- projects/hslayers/config/config.service.ts
Add possiblity to fitler units and sensors via HsConfig `senslog.filter` object .
You can now either:
- set `default` property with a value of list of `sensor_id`s which would filter all units and show only the sensors listed
-  whitelist each sensor idividually by setting up key - value pair on the config object. Accepted values for this option are either `all` or `string[]` . 
> Sensor units and sensors filtering

- projects/hslayers/common/layers/hs.source.SparqlJson.ts
- projects/hslayers/components/layer-manager/widgets/legend-widget.component.html
- projects/hslayers/components/legend/legend-custom-category.type.ts
- projects/hslayers/components/legend/legend-layer-static/legend-layer-static.component.ts
- projects/hslayers/components/legend/legend-layer/legend-layer.component.html
- projects/hslayers/components/legend/legend-layer/legend-layer.component.ts
- projects/hslayers/components/legend/legend.component.html
- projects/hslayers/components/legend/legend.component.ts
- projects/hslayers/components/legend/public-api.ts
- projects/hslayers/components/print/print-legend.service.ts
- projects/hslayers/test/legend-layer.spec.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
This change standardises de facto utilised way how to pass a custom legend via a Source (sub)class into the legend panel. It now uses custom property `legendCategories` and expected format is described in a type definition.
As an enhancement, the category can now also display custom icon (any image) instead of just colour rectangle.
Related to nature-based-solutions app.
> Allow to specify custom legend categories

- projects/hslayers/components/layer-manager/layer-manager.component.html
- projects/hslayers/services/layer-manager/layer-manager-folder.service.ts
- projects/hslayers/services/layer-manager/layer-manager.service.ts
- projects/hslayers/services/layer-shifting/layer-shifting.service.ts
- fix broken reset map button
- update folder order on layer reorder
fixes #5009
> Reset map button & order of folders

- projects/hslayers-cesium/src/hscesium-layers.service.ts
- projects/hslayers/services/map/map.service.ts
- Add axis orientation info to EPSG:3035 definition to allow its usage with WMS 1.3.0
#5093 
> refactor(map): Add axis orientation info to EPSG:3035 definition

- projects/hslayers/assets/locales/cs.json
- projects/hslayers/assets/locales/en.json
- projects/hslayers/assets/locales/lv.json
- projects/hslayers/assets/locales/sk.json
- projects/hslayers/components/layer-manager/widgets/idw-widget.component.ts
- projects/hslayers/components/styler/add-colormap.component.html
- projects/hslayers/components/styler/add-colormap.component.ts
- projects/hslayers/components/styler/filters/comparison-filter.component.html
- projects/hslayers/components/styler/filters/comparison-filter.component.ts
- projects/hslayers/components/styler/filters/filters.component.ts
- projects/hslayers/components/styler/styles.module.ts
- projects/hslayers/services/styler/styler.service.ts
- projects/hslayers/services/utils/layer-utils.service.ts
- projects/hslayers/test/layer-manager/layer-selector.service.mock.ts
- projects/hslayers/test/layer-utils.service.mock.ts
- projects/hslayers/test/styler/filters/comparison-filter.spec.ts
- projects/hslayers/test/styler/filters/filters.component.spec.ts
- String based attributes for style comaprison filter along with some unit tests
- Configurable number of color map categories
-  Fixes bug where styler rule removal created new instance of rule thus disconnecting stylerService.styleObject used to produce SLD from styler UI
closes #5152 
closes #4886
> String based attributes for style comparison filter & configurable number of color map categories

- projects/hslayers/components/layer-manager/dimensions/date-preformat.pipe.ts
- projects/hslayers/components/layer-manager/dimensions/layer-manager-time-editor.component.html
- projects/hslayers/components/layer-manager/layer-manager.module.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
Fix formatting of values like 20230925 which are incorrectly interpreted as milliseconds since 1970 epoch by the Angular's date pipe.
#5159 
> WMS-t formatting

- projects/hslayers/common/layers/hs.source.interpolated.ts
Indicate no data state of IDW layers for the purposes of [info4agro](https://info4agro.com) app.
- overwriting `onImageData` method of IDW class
-  empty canvas/missing data is guesstimated from array of rgba values. Since this data tends to be quite large (easily 10 of thousands of array items) `isImageDataMostlyEmpty` method check only 4pixels for each of the 13 defined positions placed across the image.
https://github.com/LESPROJEKT/info4agro/issues/46
> refactor(IDW): Indicate no data state on canvas

- projects/hslayers/assets/locales/sk.json
- projects/hslayers/common/panels/panel-header/panel-header.component.ts
- projects/hslayers/config/config.service.ts
- projects/hslayers/services/language/custom-translate.service.ts
- projects/hslayers/services/language/language.service.ts
- projects/hslayers/services/layout/layout.service.ts
- projects/hslayers/test/config.service.mock.ts
- projects/test-app/src/hslayers-app/hslayers-app.component.ts
- Set default panel via HsConfig.
- Refactor WebpackTranslateLoader of CustomTranslationService to use observables instead of promises
- create `loadedViaInitializator` array which can be populated by consumer appliacation to prevent translations loaded via APP_INITIALIZER handler to get reloaded (normaly we use this reload to load translationOverrides)
closes #5215 
> Set default panel via HsConfig, language updates

- .githooks/pre-commit
- .github/workflows/check-focused-tests.yml
- Add new GitHub Actions workflow that checks for the presence of focused tests (fdescribe and fit) within the projects/hslayers/test directory. Ensures that focused tests do not make it into the main codebase.
> Add GitHub Workflow to Detect Focused Tests (fdescribe and fit) in Test Directory

- projects/hslayers/components/add-data/common/url/details/details.component.html
- projects/hslayers/components/layer-manager/layer-manager.component.html
- projects/hslayers/components/layer-manager/layer-manager.component.ts
- projects/hslayers/components/layer-manager/widgets/layer-folder-widget/layer-folder-widget.component.ts
- projects/hslayers/components/map-swipe/map-swipe.service.ts
- projects/hslayers/services/add-data/common-file.service.ts
- projects/hslayers/services/add-data/url/add-data-ows.service.ts
- projects/hslayers/services/add-data/url/arcgis.service.ts
- projects/hslayers/services/add-data/url/wms.service.ts
- projects/hslayers/services/layer-manager/layer-manager-folder.service.ts
- projects/hslayers/services/layer-manager/layer-manager.service.ts
- projects/hslayers/services/layer-shifting/layer-shifting.service.ts
- projects/hslayers/test/layer-manager/layer-manager.folder.service.spec.ts
- projects/hslayers/types/add-data/data-object.type.ts
- projects/hslayers/types/compositions/composition-layer-options.type.ts
Fixes for few bugs:
-  messy rendering of map-swipe layers caused by swipe position not set correctly
-  Sort layers inside folders. Currently only folders were sorted, layers themselves where displayed in inital order
-  Layers not being removed from map when executed from catalgoue as a result of incorrectly set layer name. 
Along that :
- give priority to the property values in layerOptions over those in service defults
- Unify use_tiles and useTiles properties used in add-data
> Fixes v15 - swipe layer render, map layers order, catalogue remove

- projects/hslayers/common/panels/panel-container.component.ts
- projects/hslayers/common/panels/panel-container.service.interface.ts
- projects/hslayers/components/draw/draw-toolbar/draw-toolbar.component.html
- projects/hslayers/components/draw/draw-toolbar/draw-toolbar.component.ts
- projects/hslayers/config/config.service.ts
- projects/hslayers/services/draw/draw.service.ts
- projects/hslayers/services/panel-constructor/overlay-constructor.service.ts
- projects/hslayers/services/panel-constructor/panel-constructor.service.ts
- projects/hslayers/services/panels/panel-container.service.ts
- projects/hslayers/services/utils/layer-utils.service.ts
- fill drawable layers on when draw tooblar is opened. In sidebar layers are updated on mainPanel change
- predictable toolbar tools order defined by componentEnabled keys order. `search` -> `draw` -> `measure` by default
closes #5355 
closes #5348
> Toolbar updates

- projects/hslayers/components/layer-manager/editor/sublayers/layer-editor-sub-layer.service.ts
- projects/hslayers/services/add-data/catalogue/catalogue.service.ts
- projects/hslayers/services/add-data/common.service.ts
- projects/hslayers/services/add-data/url/wfs.service.ts
- projects/hslayers/services/add-data/url/wms.service.ts
- projects/hslayers/services/compositions/layer-parser.service.ts
- projects/hslayers/services/layer-manager/layer-manager-copy-layer.service.ts
- projects/hslayers/services/save-map/save-map.service.ts
- projects/hslayers/test/data/service-endpoints.ts
- projects/hslayers/types/add-data/ows-connection.type.ts
- better typing for connectToOws 
- sublayers for arcgis layers from compositions. Can be defined as comma separated values of ids or titles
```
{
...
"className": "ArcGISRest",
"subLayers": "2,5,8",
"title": "Správní členĕní",
"url": "https://dmvs.kraj-lbc.cz/proxybasic/rest/services/RUIAN/Spravni_cleneni/MapServer",0
...
}
```
> Arcgis sublayers

- projects/hslayers/components/query/default-info-panel-body/default-info-panel-body.component.html
- projects/hslayers/components/query/query-wms.service.ts
- projects/hslayers/css/hslayers-ng.scss
- projects/hslayers/services/query/query-base.service.ts
- fix WMS query info which respond with HTML  should not be stacked in between different queries
fixes #5476 
> WMS feature info no heritage

- projects/hslayers/components/layer-manager/editor/layer-editor.component.ts
- projects/hslayers/components/layer-manager/editor/widget-config.ts
- projects/hslayers/config/config.service.ts
Use `layerEditorWidgetsEnabled` to disable all widgets
Use `layerEditorWidgets` ton disable individual widgets eg:
```
layerEditorWidgets: {
layerType: false
}
```
fixes #5426 
> feat: Layer editor widgets - configurable

- eslint.config.mjs
- projects/hslayers-cesium/src/hscesium-camera.service.ts
- projects/hslayers-cesium/src/hscesium-layers.service.ts
- projects/hslayers-cesium/src/picker.service.ts
This fixes silent fail of transform function with invalid projections introduced in 4c2c3b0
none
> Valid projection for transform in Cesium
